<div class='alert alert-warning'>

NumPy's interactive examples are experimental and may not always work as expected, with high load times especially on low-resource platforms, and the version of NumPy might not be in sync with the one you are browsing the documentation for. If you encounter any issues, please report them on the [NumPy issue tracker](https://github.com/numpy/numpy/issues).

</div>

In [ ]:
import numpy as np
a = np.zeros((3, 3), int)
np.fill_diagonal(a, 5)
a

array([[5, 0, 0],
       [0, 5, 0],
       [0, 0, 5]])

The same function can operate on a 4-D array:


In [ ]:
a = np.zeros((3, 3, 3, 3), int)
np.fill_diagonal(a, 4)

We only show a few blocks for clarity:


In [ ]:
a[0, 0]

array([[4, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [ ]:
a[1, 1]

array([[0, 0, 0],
       [0, 4, 0],
       [0, 0, 0]])

In [ ]:
a[2, 2]

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 4]])

The wrap option affects only tall matrices:


In [ ]:
# tall matrices no wrap
a = np.zeros((5, 3), int)
np.fill_diagonal(a, 4)
a

array([[4, 0, 0],
       [0, 4, 0],
       [0, 0, 4],
       [0, 0, 0],
       [0, 0, 0]])

In [ ]:
# tall matrices wrap
a = np.zeros((5, 3), int)
np.fill_diagonal(a, 4, wrap=True)
a

array([[4, 0, 0],
       [0, 4, 0],
       [0, 0, 4],
       [0, 0, 0],
       [4, 0, 0]])

In [ ]:
# wide matrices
a = np.zeros((3, 5), int)
np.fill_diagonal(a, 4, wrap=True)
a

array([[4, 0, 0, 0, 0],
       [0, 4, 0, 0, 0],
       [0, 0, 4, 0, 0]])

The anti-diagonal can be filled by reversing the order of elements
using either `numpy.flipud` or `numpy.fliplr`.


In [ ]:
a = np.zeros((3, 3), int);
np.fill_diagonal(np.fliplr(a), [1,2,3])  # Horizontal flip
a

array([[0, 0, 1],
       [0, 2, 0],
       [3, 0, 0]])

In [ ]:
np.fill_diagonal(np.flipud(a), [1,2,3])  # Vertical flip
a

array([[0, 0, 3],
       [0, 2, 0],
       [1, 0, 0]])

Note that the order in which the diagonal is filled varies depending
on the flip function.