<div class='alert alert-warning'>

NumPy's interactive examples are experimental and may not always work as expected, with high load times especially on low-resource platforms, , and the version of NumPy might not be in sync with the one you are browsing the documentation for. If you encounter any issues, please report them on the [NumPy issue tracker](https://github.com/numpy/numpy/issues).

</div>

In [ ]:
import numpy as np

Store data to disk, and load it again:


In [ ]:
np.save('/tmp/123', np.array([[1, 2, 3], [4, 5, 6]]))
np.load('/tmp/123.npy')

array([[1, 2, 3],
       [4, 5, 6]])

Store compressed data to disk, and load it again:


In [ ]:
a=np.array([[1, 2, 3], [4, 5, 6]])
b=np.array([1, 2])
np.savez('/tmp/123.npz', a=a, b=b)
data = np.load('/tmp/123.npz')
data['a']

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
data['b']

array([1, 2])

In [ ]:
data.close()

Mem-map the stored array, and then access the second row
directly from disk:


In [ ]:
X = np.load('/tmp/123.npy', mmap_mode='r')
X[1, :]

memmap([4, 5, 6])