<div class='alert alert-warning'>

NumPy's interactive examples are experimental and may not always work as expected, with high load times especially on low-resource platforms, , and the version of NumPy might not be in sync with the one you are browsing the documentation for. If you encounter any issues, please report them on the [NumPy issue tracker](https://github.com/numpy/numpy/issues).

</div>

In [ ]:
import numpy as np

Create a 4 by 4 array.


In [ ]:
a = np.arange(16).reshape(4, 4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

Get the indices of the diagonal elements.


In [ ]:
di = np.diag_indices_from(a)
di

(array([0, 1, 2, 3]), array([0, 1, 2, 3]))

In [ ]:
a[di]

array([ 0,  5, 10, 15])

This is simply syntactic sugar for diag_indices.


In [ ]:
np.diag_indices(a.shape[0])

(array([0, 1, 2, 3]), array([0, 1, 2, 3]))