<div class='alert alert-warning'>

NumPy's interactive examples are experimental and may not always work as expected, with high load times especially on low-resource platforms, , and the version of NumPy might not be in sync with the one you are browsing the documentation for. If you encounter any issues, please report them on the [NumPy issue tracker](https://github.com/numpy/numpy/issues).

</div>

In [ ]:
import numpy as np
a = np.array([[1, 2], [3, 4], [5, 6]])
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
np.compress([0, 1], a, axis=0)

array([[3, 4]])

In [ ]:
np.compress([False, True, True], a, axis=0)

array([[3, 4],
       [5, 6]])

In [ ]:
np.compress([False, True], a, axis=1)

array([[2],
       [4],
       [6]])

Working on the flattened array does not return slices along an axis but
selects elements.


In [ ]:
np.compress([False, True], a)

array([2])