<div class='alert alert-warning'>

NumPy's interactive examples are experimental and may not always work as expected, with high load times especially on low-resource platforms, , and the version of NumPy might not be in sync with the one you are browsing the documentation for. If you encounter any issues, please report them on the [NumPy issue tracker](https://github.com/numpy/numpy/issues).

</div>

In [ ]:
import numpy as np
np.maximum([2, 3, 4], [1, 5, 2])

array([2, 5, 4])

In [ ]:
np.maximum(np.eye(2), [0.5, 2]) # broadcasting

array([[ 1. ,  2. ],
       [ 0.5,  2. ]])

In [ ]:
np.maximum([np.nan, 0, np.nan], [0, np.nan, np.nan])

array([nan, nan, nan])

In [ ]:
np.maximum(np.inf, 1)

inf