<div class='alert alert-warning'>

NumPy's interactive examples are experimental and may not always work as expected, with high load times especially on low-resource platforms, and the version of NumPy might not be in sync with the one you are browsing the documentation for. If you encounter any issues, please report them on the [NumPy issue tracker](https://github.com/numpy/numpy/issues).

</div>

In [ ]:
import numpy as np

Cube each element in an array.


In [ ]:
x1 = np.arange(6)
x1

[0, 1, 2, 3, 4, 5]

In [ ]:
np.power(x1, 3)

array([  0,   1,   8,  27,  64, 125])

Raise the bases to different exponents.


In [ ]:
x2 = [1.0, 2.0, 3.0, 3.0, 2.0, 1.0]
np.power(x1, x2)

array([  0.,   1.,   8.,  27.,  16.,   5.])

The effect of broadcasting.


In [ ]:
x2 = np.array([[1, 2, 3, 3, 2, 1], [1, 2, 3, 3, 2, 1]])
x2

array([[1, 2, 3, 3, 2, 1],
       [1, 2, 3, 3, 2, 1]])

In [ ]:
np.power(x1, x2)

array([[ 0,  1,  8, 27, 16,  5],
       [ 0,  1,  8, 27, 16,  5]])

The ``**`` operator can be used as a shorthand for ``np.power`` on
ndarrays.


In [ ]:
x2 = np.array([1, 2, 3, 3, 2, 1])
x1 = np.arange(6)
x1 ** x2

array([ 0,  1,  8, 27, 16,  5])

Negative values raised to a non-integral value will result in ``nan``
(and a warning will be generated).


In [ ]:
x3 = np.array([-1.0, -4.0])
with np.errstate(invalid='ignore'):
    p = np.power(x3, 1.5)

p

array([nan, nan])

To get complex results, give the argument ``dtype=complex``.


In [ ]:
np.power(x3, 1.5, dtype=complex)

array([-1.83697020e-16-1.j, -1.46957616e-15-8.j])