<div class='alert alert-warning'>

NumPy's interactive examples are experimental and may not always work as expected, with high load times especially on low-resource platforms, , and the version of NumPy might not be in sync with the one you are browsing the documentation for. If you encounter any issues, please report them on the [NumPy issue tracker](https://github.com/numpy/numpy/issues).

</div>

In [ ]:
import numpy as np
a = np.arange(4).reshape(2,2)
a

array([[0, 1],
       [2, 3]])

In [ ]:
a.diagonal()

array([0, 3])

In [ ]:
a.diagonal(1)

array([1])

A 3-D example:


In [ ]:
a = np.arange(8).reshape(2,2,2); a

array([[[0, 1],
        [2, 3]],
       [[4, 5],
        [6, 7]]])

In [ ]:
a.diagonal(0,  # Main diagonals of two arrays created by skipping
           0,  # across the outer(left)-most axis last and
           1)  # the "middle" (row) axis first.

array([[0, 6],
       [1, 7]])

The sub-arrays whose main diagonals we just obtained; note that each
corresponds to fixing the right-most (column) axis, and that the
diagonals are "packed" in rows.


In [ ]:
a[:,:,0]  # main diagonal is [0 6]

array([[0, 2],
       [4, 6]])

In [ ]:
a[:,:,1]  # main diagonal is [1 7]

array([[1, 3],
       [5, 7]])

The anti-diagonal can be obtained by reversing the order of elements
using either `numpy.flipud` or `numpy.fliplr`.


In [ ]:
a = np.arange(9).reshape(3, 3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
np.fliplr(a).diagonal()  # Horizontal flip

array([2, 4, 6])

In [ ]:
np.flipud(a).diagonal()  # Vertical flip

array([6, 4, 2])

Note that the order in which the diagonal is retrieved varies depending
on the flip function.