<div class='alert alert-warning'>

NumPy's interactive examples are experimental and may not always work as expected, with high load times especially on low-resource platforms, and the version of NumPy might not be in sync with the one you are browsing the documentation for. If you encounter any issues, please report them on the [NumPy issue tracker](https://github.com/numpy/numpy/issues).

</div>

In [ ]:
from numpy.polynomial.polynomial import polyvalfromroots
polyvalfromroots(1, [1, 2, 3])

0.0

In [ ]:
a = np.arange(4).reshape(2, 2)
a

array([[0, 1],
       [2, 3]])

In [ ]:
polyvalfromroots(a, [-1, 0, 1])

array([[-0.,   0.],
       [ 6.,  24.]])

In [ ]:
r = np.arange(-2, 2).reshape(2,2)  # multidimensional coefficients
r # each column of r defines one polynomial

array([[-2, -1],
       [ 0,  1]])

In [ ]:
b = [-2, 1]
polyvalfromroots(b, r, tensor=True)

array([[-0.,  3.],
       [ 3., 0.]])

In [ ]:
polyvalfromroots(b, r, tensor=False)

array([-0.,  0.])