<div class='alert alert-warning'>

NumPy's interactive examples are experimental and may not always work as expected, with high load times especially on low-resource platforms, , and the version of NumPy might not be in sync with the one you are browsing the documentation for. If you encounter any issues, please report them on the [NumPy issue tracker](https://github.com/numpy/numpy/issues).

</div>

In [ ]:
import numpy as np
import numpy.ma as ma
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [ ]:
a = ma.masked_where(a < 3, a)
a

masked_array(data=[--, --, --, 3, 4],
             mask=[ True,  True,  True, False, False],
       fill_value=999999)

In [ ]:
ma.set_fill_value(a, -999)
a

masked_array(data=[--, --, --, 3, 4],
             mask=[ True,  True,  True, False, False],
       fill_value=-999)

Nothing happens if `a` is not a masked array.


In [ ]:
a = list(range(5))
a

[0, 1, 2, 3, 4]

In [ ]:
ma.set_fill_value(a, 100)
a

[0, 1, 2, 3, 4]

In [ ]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [ ]:
ma.set_fill_value(a, 100)
a

array([0, 1, 2, 3, 4])