<div class='alert alert-warning'>

NumPy's interactive examples are experimental and may not always work as expected, with high load times especially on low-resource platforms, , and the version of NumPy might not be in sync with the one you are browsing the documentation for. If you encounter any issues, please report them on the [NumPy issue tracker](https://github.com/numpy/numpy/issues).

</div>

In [ ]:
import numpy as np
a = np.arange(10).reshape(2, 5)
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [ ]:
ixgrid = np.ix_([0, 1], [2, 4])
ixgrid

(array([[0],
       [1]]), array([[2, 4]]))

In [ ]:
ixgrid[0].shape, ixgrid[1].shape

((2, 1), (1, 2))

In [ ]:
a[ixgrid]

array([[2, 4],
       [7, 9]])

In [ ]:
ixgrid = np.ix_([True, True], [2, 4])
a[ixgrid]

array([[2, 4],
       [7, 9]])

In [ ]:
ixgrid = np.ix_([True, True], [False, False, True, False, True])
a[ixgrid]

array([[2, 4],
       [7, 9]])