<div class='alert alert-warning'>

NumPy's interactive examples are experimental and may not always work as expected, with high load times especially on low-resource platforms, , and the version of NumPy might not be in sync with the one you are browsing the documentation for. If you encounter any issues, please report them on the [NumPy issue tracker](https://github.com/numpy/numpy/issues).

</div>

In [ ]:
import numpy as np
a = np.arange(6).reshape(2,3) + 10
a

array([[10, 11, 12],
       [13, 14, 15]])

In [ ]:
np.argmin(a)

0

In [ ]:
np.argmin(a, axis=0)

array([0, 0, 0])

In [ ]:
np.argmin(a, axis=1)

array([0, 0])

Indices of the minimum elements of a N-dimensional array:


In [ ]:
ind = np.unravel_index(np.argmin(a, axis=None), a.shape)
ind

(0, 0)

In [ ]:
a[ind]

10

In [ ]:
b = np.arange(6) + 10
b[4] = 10
b

array([10, 11, 12, 13, 10, 15])

In [ ]:
np.argmin(b)  # Only the first occurrence is returned.

0

In [ ]:
x = np.array([[4,2,3], [1,0,3]])
index_array = np.argmin(x, axis=-1)
# Same as np.amin(x, axis=-1, keepdims=True)
np.take_along_axis(x, np.expand_dims(index_array, axis=-1), axis=-1)

array([[2],
       [0]])

In [ ]:
# Same as np.amax(x, axis=-1)
np.take_along_axis(x, np.expand_dims(index_array, axis=-1),
    axis=-1).squeeze(axis=-1)

array([2, 0])

Setting `keepdims` to `True`,


In [ ]:
x = np.arange(24).reshape((2, 3, 4))
res = np.argmin(x, axis=1, keepdims=True)
res.shape

(2, 1, 4)