<div class='alert alert-warning'>

NumPy's interactive examples are experimental and may not always work as expected, with high load times especially on low-resource platforms, and the version of NumPy might not be in sync with the one you are browsing the documentation for. If you encounter any issues, please report them on the [NumPy issue tracker](https://github.com/numpy/numpy/issues).

</div>

In [ ]:
a = np.arange(25).reshape(5,5)
b = np.arange(5)
c = np.arange(6).reshape(2,3)

Trace of a matrix:


In [ ]:
np.einsum('ii', a)

60

In [ ]:
np.einsum(a, [0,0])

60

In [ ]:
np.trace(a)

60

Extract the diagonal (requires explicit form):


In [ ]:
np.einsum('ii->i', a)

array([ 0,  6, 12, 18, 24])

In [ ]:
np.einsum(a, [0,0], [0])

array([ 0,  6, 12, 18, 24])

In [ ]:
np.diag(a)

array([ 0,  6, 12, 18, 24])

Sum over an axis (requires explicit form):


In [ ]:
np.einsum('ij->i', a)

array([ 10,  35,  60,  85, 110])

In [ ]:
np.einsum(a, [0,1], [0])

array([ 10,  35,  60,  85, 110])

In [ ]:
np.sum(a, axis=1)

array([ 10,  35,  60,  85, 110])

For higher dimensional arrays summing a single axis can be done
with ellipsis:


In [ ]:
np.einsum('...j->...', a)

array([ 10,  35,  60,  85, 110])

In [ ]:
np.einsum(a, [Ellipsis,1], [Ellipsis])

array([ 10,  35,  60,  85, 110])

Compute a matrix transpose, or reorder any number of axes:


In [ ]:
np.einsum('ji', c)

array([[0, 3],
       [1, 4],
       [2, 5]])

In [ ]:
np.einsum('ij->ji', c)

array([[0, 3],
       [1, 4],
       [2, 5]])

In [ ]:
np.einsum(c, [1,0])

array([[0, 3],
       [1, 4],
       [2, 5]])

In [ ]:
np.transpose(c)

array([[0, 3],
       [1, 4],
       [2, 5]])

Vector inner products:


In [ ]:
np.einsum('i,i', b, b)

30

In [ ]:
np.einsum(b, [0], b, [0])

30

In [ ]:
np.inner(b,b)

30

Matrix vector multiplication:


In [ ]:
np.einsum('ij,j', a, b)

array([ 30,  80, 130, 180, 230])

In [ ]:
np.einsum(a, [0,1], b, [1])

array([ 30,  80, 130, 180, 230])

In [ ]:
np.dot(a, b)

array([ 30,  80, 130, 180, 230])

In [ ]:
np.einsum('...j,j', a, b)

array([ 30,  80, 130, 180, 230])

Broadcasting and scalar multiplication:


In [ ]:
np.einsum('..., ...', 3, c)

array([[ 0,  3,  6],
       [ 9, 12, 15]])

In [ ]:
np.einsum(',ij', 3, c)

array([[ 0,  3,  6],
       [ 9, 12, 15]])

In [ ]:
np.einsum(3, [Ellipsis], c, [Ellipsis])

array([[ 0,  3,  6],
       [ 9, 12, 15]])

In [ ]:
np.multiply(3, c)

array([[ 0,  3,  6],
       [ 9, 12, 15]])

Vector outer product:


In [ ]:
np.einsum('i,j', np.arange(2)+1, b)

array([[0, 1, 2, 3, 4],
       [0, 2, 4, 6, 8]])

In [ ]:
np.einsum(np.arange(2)+1, [0], b, [1])

array([[0, 1, 2, 3, 4],
       [0, 2, 4, 6, 8]])

In [ ]:
np.outer(np.arange(2)+1, b)

array([[0, 1, 2, 3, 4],
       [0, 2, 4, 6, 8]])

Tensor contraction:


In [ ]:
a = np.arange(60.).reshape(3,4,5)
b = np.arange(24.).reshape(4,3,2)
np.einsum('ijk,jil->kl', a, b)

array([[4400., 4730.],
       [4532., 4874.],
       [4664., 5018.],
       [4796., 5162.],
       [4928., 5306.]])

In [ ]:
np.einsum(a, [0,1,2], b, [1,0,3], [2,3])

array([[4400., 4730.],
       [4532., 4874.],
       [4664., 5018.],
       [4796., 5162.],
       [4928., 5306.]])

In [ ]:
np.tensordot(a,b, axes=([1,0],[0,1]))

array([[4400., 4730.],
       [4532., 4874.],
       [4664., 5018.],
       [4796., 5162.],
       [4928., 5306.]])

Writeable returned arrays (since version 1.10.0):


In [ ]:
a = np.zeros((3, 3))
np.einsum('ii->i', a)[:] = 1
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Example of ellipsis use:


In [ ]:
a = np.arange(6).reshape((3,2))
b = np.arange(12).reshape((4,3))
np.einsum('ki,jk->ij', a, b)

array([[10, 28, 46, 64],
       [13, 40, 67, 94]])

In [ ]:
np.einsum('ki,...k->i...', a, b)

array([[10, 28, 46, 64],
       [13, 40, 67, 94]])

In [ ]:
np.einsum('k...,jk', a, b)

array([[10, 28, 46, 64],
       [13, 40, 67, 94]])

Chained array operations. For more complicated contractions, speed ups
might be achieved by repeatedly computing a 'greedy' path or pre-computing
the 'optimal' path and repeatedly applying it, using an `einsum_path`
insertion (since version 1.12.0). Performance improvements can be
particularly significant with larger arrays:


In [ ]:
a = np.ones(64).reshape(2,4,8)

Basic `einsum`: ~1520ms  (benchmarked on 3.1GHz Intel i5.)


In [ ]:
for iteration in range(500):
    _ = np.einsum('ijk,ilm,njm,nlk,abc->',a,a,a,a,a)

Sub-optimal `einsum` (due to repeated path calculation time): ~330ms


In [ ]:
for iteration in range(500):
    _ = np.einsum('ijk,ilm,njm,nlk,abc->',a,a,a,a,a,
        optimize='optimal')

Greedy `einsum` (faster optimal path approximation): ~160ms


In [ ]:
for iteration in range(500):
    _ = np.einsum('ijk,ilm,njm,nlk,abc->',a,a,a,a,a, optimize='greedy')

Optimal `einsum` (best usage pattern in some use cases): ~110ms


In [ ]:
path = np.einsum_path('ijk,ilm,njm,nlk,abc->',a,a,a,a,a, 
    optimize='optimal')[0]
for iteration in range(500):
    _ = np.einsum('ijk,ilm,njm,nlk,abc->',a,a,a,a,a, optimize=path)