<div class='alert alert-warning'>

NumPy's interactive examples are experimental and may not always work as expected, with high load times especially on low-resource platforms, , and the version of NumPy might not be in sync with the one you are browsing the documentation for. If you encounter any issues, please report them on the [NumPy issue tracker](https://github.com/numpy/numpy/issues).

</div>

In [ ]:
import numpy as np
x = np.arange(6, dtype=int)
np.full_like(x, 1)

array([1, 1, 1, 1, 1, 1])

In [ ]:
np.full_like(x, 0.1)

array([0, 0, 0, 0, 0, 0])

In [ ]:
np.full_like(x, 0.1, dtype=np.double)

array([0.1, 0.1, 0.1, 0.1, 0.1, 0.1])

In [ ]:
np.full_like(x, np.nan, dtype=np.double)

array([nan, nan, nan, nan, nan, nan])

In [ ]:
y = np.arange(6, dtype=np.double)
np.full_like(y, 0.1)

array([0.1, 0.1, 0.1, 0.1, 0.1, 0.1])

In [ ]:
y = np.zeros([2, 2, 3], dtype=int)
np.full_like(y, [0, 0, 255])

array([[[  0,   0, 255],
        [  0,   0, 255]],
       [[  0,   0, 255],
        [  0,   0, 255]]])