<div class='alert alert-warning'>

NumPy's interactive examples are experimental and may not always work as expected, with high load times especially on low-resource platforms, and the version of NumPy might not be in sync with the one you are browsing the documentation for. If you encounter any issues, please report them on the [NumPy issue tracker](https://github.com/numpy/numpy/issues).

</div>

In [ ]:
import numpy as np
x = np.array([(-1, 2)], dtype=[('a', np.int8), ('b', np.int8)])

Viewing array data using a different type and dtype:


In [ ]:
nonneg = np.dtype([("a", np.uint8), ("b", np.uint8)])
y = x.view(dtype=nonneg, type=np.recarray)
x["a"]

array([-1], dtype=int8)

In [ ]:
y.a

array([255], dtype=uint8)

Creating a view on a structured array so it can be used in calculations


In [ ]:
x = np.array([(1, 2),(3,4)], dtype=[('a', np.int8), ('b', np.int8)])
xv = x.view(dtype=np.int8).reshape(-1,2)
xv

array([[1, 2],
       [3, 4]], dtype=int8)

In [ ]:
xv.mean(0)

array([2.,  3.])

Making changes to the view changes the underlying array


In [ ]:
xv[0,1] = 20
x

array([(1, 20), (3,  4)], dtype=[('a', 'i1'), ('b', 'i1')])

Using a view to convert an array to a recarray:


In [ ]:
z = x.view(np.recarray)
z.a

array([1, 3], dtype=int8)

Views share data:


In [ ]:
x[0] = (9, 10)
z[0]

np.record((9, 10), dtype=[('a', 'i1'), ('b', 'i1')])

Views that change the dtype size (bytes per entry) should normally be
avoided on arrays defined by slices, transposes, fortran-ordering, etc.:


In [ ]:
x = np.array([[1, 2, 3], [4, 5, 6]], dtype=np.int16)
y = x[:, ::2]
y

array([[1, 3],
       [4, 6]], dtype=int16)

In [ ]:
y.view(dtype=[('width', np.int16), ('length', np.int16)])

Traceback (most recent call last):
    ...
ValueError: To change to a dtype of a different size, the last axis must be contiguous

In [ ]:
z = y.copy()
z.view(dtype=[('width', np.int16), ('length', np.int16)])

array([[(1, 3)],
       [(4, 6)]], dtype=[('width', '<i2'), ('length', '<i2')])

However, views that change dtype are totally fine for arrays with a
contiguous last axis, even if the rest of the axes are not C-contiguous:


In [ ]:
x = np.arange(2 * 3 * 4, dtype=np.int8).reshape(2, 3, 4)
x.transpose(1, 0, 2).view(np.int16)

array([[[ 256,  770],
        [3340, 3854]],
<BLANKLINE>
       [[1284, 1798],
        [4368, 4882]],
<BLANKLINE>
       [[2312, 2826],
        [5396, 5910]]], dtype=int16)