<div class='alert alert-warning'>

NumPy's interactive examples are experimental and may not always work as expected, with high load times especially on low-resource platforms, , and the version of NumPy might not be in sync with the one you are browsing the documentation for. If you encounter any issues, please report them on the [NumPy issue tracker](https://github.com/numpy/numpy/issues).

</div>

In [ ]:
import numpy as np
np.isfinite(1)

True

In [ ]:
np.isfinite(0)

True

In [ ]:
np.isfinite(np.nan)

False

In [ ]:
np.isfinite(np.inf)

False

In [ ]:
np.isfinite(-np.inf)

False

In [ ]:
np.isfinite([np.log(-1.),1.,np.log(0)])

array([False,  True, False])

In [ ]:
x = np.array([-np.inf, 0., np.inf])
y = np.array([2, 2, 2])
np.isfinite(x, y)

array([0, 1, 0])

In [ ]:
y

array([0, 1, 0])