<div class='alert alert-warning'>

NumPy's interactive examples are experimental and may not always work as expected, with high load times especially on low-resource platforms, and the version of NumPy might not be in sync with the one you are browsing the documentation for. If you encounter any issues, please report them on the [NumPy issue tracker](https://github.com/numpy/numpy/issues).

</div>

In [ ]:
from numpy.polynomial import polynomial as P
c = (1, 2, 3)
P.polyint(c)  # should return array([0, 1, 1, 1])

array([0.,  1.,  1.,  1.])

In [ ]:
P.polyint(c, 3)  # should return array([0, 0, 0, 1/6, 1/12, 1/20])

 array([ 0.        ,  0.        ,  0.        ,  0.16666667,  0.08333333, # may vary
         0.05      ])

In [ ]:
P.polyint(c, k=3)  # should return array([3, 1, 1, 1])

array([3.,  1.,  1.,  1.])

In [ ]:
P.polyint(c,lbnd=-2)  # should return array([6, 1, 1, 1])

array([6.,  1.,  1.,  1.])

In [ ]:
P.polyint(c,scl=-2)  # should return array([0, -2, -2, -2])

array([ 0., -2., -2., -2.])