<div class='alert alert-warning'>

NumPy's interactive examples are experimental and may not always work as expected, with high load times especially on low-resource platforms, , and the version of NumPy might not be in sync with the one you are browsing the documentation for. If you encounter any issues, please report them on the [NumPy issue tracker](https://github.com/numpy/numpy/issues).

</div>

In [ ]:
import numpy as np
a = np.array([[10, 7, 4], [3, 2, 1]])
a

array([[10,  7,  4],
       [ 3,  2,  1]])

In [ ]:
np.median(a)

np.float64(3.5)

In [ ]:
np.median(a, axis=0)

array([6.5, 4.5, 2.5])

In [ ]:
np.median(a, axis=1)

array([7.,  2.])

In [ ]:
np.median(a, axis=(0, 1))

np.float64(3.5)

In [ ]:
m = np.median(a, axis=0)
out = np.zeros_like(m)
np.median(a, axis=0, out=m)

array([6.5,  4.5,  2.5])

In [ ]:
m

array([6.5,  4.5,  2.5])

In [ ]:
b = a.copy()
np.median(b, axis=1, overwrite_input=True)

array([7.,  2.])

In [ ]:
assert not np.all(a==b)
b = a.copy()
np.median(b, axis=None, overwrite_input=True)

np.float64(3.5)

In [ ]:
assert not np.all(a==b)