<div class='alert alert-warning'>

NumPy's interactive examples are experimental and may not always work as expected, with high load times especially on low-resource platforms, , and the version of NumPy might not be in sync with the one you are browsing the documentation for. If you encounter any issues, please report them on the [NumPy issue tracker](https://github.com/numpy/numpy/issues).

</div>

In [ ]:
import numpy as np
c = np.array(['aAaAaA', '  aA  ', 'abBABba'])
c

array(['aAaAaA', '  aA  ', 'abBABba'], dtype='<U7')

In [ ]:
np.strings.count(c, 'A')

array([3, 1, 1])

In [ ]:
np.strings.count(c, 'aA')

array([3, 1, 0])

In [ ]:
np.strings.count(c, 'A', start=1, end=4)

array([2, 1, 1])

In [ ]:
np.strings.count(c, 'A', start=1, end=3)

array([1, 0, 0])