<div class='alert alert-warning'>

NumPy's interactive examples are experimental and may not always work as expected, with high load times especially on low-resource platforms, and the version of NumPy might not be in sync with the one you are browsing the documentation for. If you encounter any issues, please report them on the [NumPy issue tracker](https://github.com/numpy/numpy/issues).

</div>

In [ ]:
import numpy as np

Use the trapezoidal rule on evenly spaced points:


In [ ]:
np.trapezoid([1, 2, 3])

4.0

The spacing between sample points can be selected by either the
``x`` or ``dx`` arguments:


In [ ]:
np.trapezoid([1, 2, 3], x=[4, 6, 8])

8.0

In [ ]:
np.trapezoid([1, 2, 3], dx=2)

8.0

Using a decreasing ``x`` corresponds to integrating in reverse:


In [ ]:
np.trapezoid([1, 2, 3], x=[8, 6, 4])

-8.0

More generally ``x`` is used to integrate along a parametric curve. We can
estimate the integral $\int_0^1 x^2 = 1/3$ using:


In [ ]:
x = np.linspace(0, 1, num=50)
y = x**2
np.trapezoid(y, x)

0.33340274885464394

Or estimate the area of a circle, noting we repeat the sample which closes
the curve:


In [ ]:
theta = np.linspace(0, 2 * np.pi, num=1000, endpoint=True)
np.trapezoid(np.cos(theta), x=np.sin(theta))

3.141571941375841

``np.trapezoid`` can be applied along a specified axis to do multiple
computations in one call:


In [ ]:
a = np.arange(6).reshape(2, 3)
a

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
np.trapezoid(a, axis=0)

array([1.5, 2.5, 3.5])

In [ ]:
np.trapezoid(a, axis=1)

array([2.,  8.])