<div class='alert alert-warning'>

NumPy's interactive examples are experimental and may not always work as expected, with high load times especially on low-resource platforms, and the version of NumPy might not be in sync with the one you are browsing the documentation for. If you encounter any issues, please report them on the [NumPy issue tracker](https://github.com/numpy/numpy/issues).

</div>

Create a `numpy.random.Generator` instance:


In [ ]:
rng = np.random.default_rng()

Create a test array:


In [ ]:
x = np.arange(24).reshape(3, 8)
x

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])

Shuffle the rows of `x`:


In [ ]:
y = rng.permuted(x, axis=1)
y

array([[ 4,  3,  6,  7,  1,  2,  5,  0],  # random
       [15, 10, 14,  9, 12, 11,  8, 13],
       [17, 16, 20, 21, 18, 22, 23, 19]])

`x` has not been modified:


In [ ]:
x

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])

To shuffle the rows of `x` in-place, pass `x` as the `out`
parameter:


In [ ]:
y = rng.permuted(x, axis=1, out=x)
x

array([[ 3,  0,  4,  7,  1,  6,  2,  5],  # random
       [ 8, 14, 13,  9, 12, 11, 15, 10],
       [17, 18, 16, 22, 19, 23, 20, 21]])

Note that when the ``out`` parameter is given, the return
value is ``out``:


In [ ]:
y is x

True