<div class='alert alert-warning'>

NumPy's interactive examples are experimental and may not always work as expected, with high load times especially on low-resource platforms, , and the version of NumPy might not be in sync with the one you are browsing the documentation for. If you encounter any issues, please report them on the [NumPy issue tracker](https://github.com/numpy/numpy/issues).

</div>

In [ ]:
import numpy as np
a = [4, 3, 5, 7, 6, 8]
indices = [0, 1, 4]
np.take(a, indices)

array([4, 3, 6])

In this example if `a` is an ndarray, "fancy" indexing can be used.


In [ ]:
a = np.array(a)
a[indices]

array([4, 3, 6])

If `indices` is not one dimensional, the output also has these dimensions.


In [ ]:
np.take(a, [[0, 1], [2, 3]])

array([[4, 3],
       [5, 7]])