<div class='alert alert-warning'>

NumPy's interactive examples are experimental and may not always work as expected, with high load times especially on low-resource platforms, and the version of NumPy might not be in sync with the one you are browsing the documentation for. If you encounter any issues, please report them on the [NumPy issue tracker](https://github.com/numpy/numpy/issues).

</div>

Note how the convolution operator flips the second array
before "sliding" the two across one another:


In [ ]:
import numpy as np
np.convolve([1, 2, 3], [0, 1, 0.5])

array([0. , 1. , 2.5, 4. , 1.5])

Only return the middle values of the convolution.
Contains boundary effects, where zeros are taken
into account:


In [ ]:
np.convolve([1,2,3],[0,1,0.5], 'same')

array([1. ,  2.5,  4. ])

The two arrays are of the same length, so there
is only one position where they completely overlap:


In [ ]:
np.convolve([1,2,3],[0,1,0.5], 'valid')

array([2.5])