<div class='alert alert-warning'>

NumPy's interactive examples are experimental and may not always work as expected, with high load times especially on low-resource platforms, , and the version of NumPy might not be in sync with the one you are browsing the documentation for. If you encounter any issues, please report them on the [NumPy issue tracker](https://github.com/numpy/numpy/issues).

</div>

In [ ]:
import numpy as np
np.round([0.37, 1.64])

array([0., 2.])

In [ ]:
np.round([0.37, 1.64], decimals=1)

array([0.4, 1.6])

In [ ]:
np.round([.5, 1.5, 2.5, 3.5, 4.5]) # rounds to nearest even value

array([0., 2., 2., 4., 4.])

In [ ]:
np.round([1,2,3,11], decimals=1) # ndarray of ints is returned

array([ 1,  2,  3, 11])

In [ ]:
np.round([1,2,3,11], decimals=-1)

array([ 0,  0,  0, 10])