<div class='alert alert-warning'>

NumPy's interactive examples are experimental and may not always work as expected, with high load times especially on low-resource platforms, and the version of NumPy might not be in sync with the one you are browsing the documentation for. If you encounter any issues, please report them on the [NumPy issue tracker](https://github.com/numpy/numpy/issues).

</div>

In [ ]:
import numpy as np
a = np.arange(6).reshape(3, 2)
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [ ]:
np.insert(a, 1, 6)

array([0, 6, 1, 2, 3, 4, 5])

In [ ]:
np.insert(a, 1, 6, axis=1)

array([[0, 6, 1],
       [2, 6, 3],
       [4, 6, 5]])

Difference between sequence and scalars,
showing how ``obj=[1]`` behaves different from ``obj=1``:


In [ ]:
np.insert(a, [1], [[7],[8],[9]], axis=1)

array([[0, 7, 1],
       [2, 8, 3],
       [4, 9, 5]])

In [ ]:
np.insert(a, 1, [[7],[8],[9]], axis=1)

array([[0, 7, 8, 9, 1],
       [2, 7, 8, 9, 3],
       [4, 7, 8, 9, 5]])

In [ ]:
np.array_equal(np.insert(a, 1, [7, 8, 9], axis=1),
               np.insert(a, [1], [[7],[8],[9]], axis=1))

True

In [ ]:
b = a.flatten()
b

array([0, 1, 2, 3, 4, 5])

In [ ]:
np.insert(b, [2, 2], [6, 7])

array([0, 1, 6, 7, 2, 3, 4, 5])

In [ ]:
np.insert(b, slice(2, 4), [7, 8])

array([0, 1, 7, 2, 8, 3, 4, 5])

In [ ]:
np.insert(b, [2, 2], [7.13, False]) # type casting

array([0, 1, 7, 0, 2, 3, 4, 5])

In [ ]:
x = np.arange(8).reshape(2, 4)
idx = (1, 3)
np.insert(x, idx, 999, axis=1)

array([[  0, 999,   1,   2, 999,   3],
       [  4, 999,   5,   6, 999,   7]])