<div class='alert alert-warning'>

NumPy's interactive examples are experimental and may not always work as expected, with high load times especially on low-resource platforms, , and the version of NumPy might not be in sync with the one you are browsing the documentation for. If you encounter any issues, please report them on the [NumPy issue tracker](https://github.com/numpy/numpy/issues).

</div>

In [ ]:
import numpy as np
np.linspace(2.0, 3.0, num=5)

array([2.  , 2.25, 2.5 , 2.75, 3.  ])

In [ ]:
np.linspace(2.0, 3.0, num=5, endpoint=False)

array([2. ,  2.2,  2.4,  2.6,  2.8])

In [ ]:
np.linspace(2.0, 3.0, num=5, retstep=True)

(array([2.  ,  2.25,  2.5 ,  2.75,  3.  ]), 0.25)

Graphical illustration:


In [ ]:
import matplotlib.pyplot as plt
N = 8
y = np.zeros(N)
x1 = np.linspace(0, 10, N, endpoint=True)
x2 = np.linspace(0, 10, N, endpoint=False)
plt.plot(x1, y, 'o')

[<matplotlib.lines.Line2D object at 0x...>]

In [ ]:
plt.plot(x2, y + 0.5, 'o')

[<matplotlib.lines.Line2D object at 0x...>]

In [ ]:
plt.ylim([-0.5, 1])

(-0.5, 1)

In [ ]:
plt.show()