<div class='alert alert-warning'>

NumPy's interactive examples are experimental and may not always work as expected, with high load times especially on low-resource platforms, , and the version of NumPy might not be in sync with the one you are browsing the documentation for. If you encounter any issues, please report them on the [NumPy issue tracker](https://github.com/numpy/numpy/issues).

</div>

In [ ]:
import numpy as np

We've seen that 13 is represented by ``00001101``.
The invert or bit-wise NOT of 13 is then:


In [ ]:
x = np.invert(np.array(13, dtype=np.uint8))
x

242

In [ ]:
np.binary_repr(x, width=8)

'11110010'

The result depends on the bit-width:


In [ ]:
x = np.invert(np.array(13, dtype=np.uint16))
x

65522

In [ ]:
np.binary_repr(x, width=16)

'1111111111110010'

When using signed integer types, the result is the bit-wise NOT of
the unsigned type, interpreted as a signed integer:


In [ ]:
np.invert(np.array([13], dtype=np.int8))

array([-14], dtype=int8)

In [ ]:
np.binary_repr(-14, width=8)

'11110010'

Booleans are accepted as well:


In [ ]:
np.invert(np.array([True, False]))

array([False,  True])

The ``~`` operator can be used as a shorthand for ``np.invert`` on
ndarrays.


In [ ]:
x1 = np.array([True, False])
~x1

array([False,  True])