<div class='alert alert-warning'>

NumPy's interactive examples are experimental and may not always work as expected, with high load times especially on low-resource platforms, , and the version of NumPy might not be in sync with the one you are browsing the documentation for. If you encounter any issues, please report them on the [NumPy issue tracker](https://github.com/numpy/numpy/issues).

</div>

In [ ]:
import numpy as np
np.zeros(5)

array([ 0.,  0.,  0.,  0.,  0.])

In [ ]:
np.zeros((5,), dtype=int)

array([0, 0, 0, 0, 0])

In [ ]:
np.zeros((2, 1))

array([[ 0.],
       [ 0.]])

In [ ]:
s = (2,2)
np.zeros(s)

array([[ 0.,  0.],
       [ 0.,  0.]])

In [ ]:
np.zeros((2,), dtype=[('x', 'i4'), ('y', 'i4')]) # custom dtype

array([(0, 0), (0, 0)],
      dtype=[('x', '<i4'), ('y', '<i4')])