<div class='alert alert-warning'>

NumPy's interactive examples are experimental and may not always work as expected, with high load times especially on low-resource platforms, , and the version of NumPy might not be in sync with the one you are browsing the documentation for. If you encounter any issues, please report them on the [NumPy issue tracker](https://github.com/numpy/numpy/issues).

</div>

1-D array examples:


In [ ]:
import numpy as np
np.add.accumulate([2, 3, 5])

array([ 2,  5, 10])

In [ ]:
np.multiply.accumulate([2, 3, 5])

array([ 2,  6, 30])

2-D array examples:


In [ ]:
I = np.eye(2)
I

array([[1.,  0.],
       [0.,  1.]])

Accumulate along axis 0 (rows), down columns:


In [ ]:
np.add.accumulate(I, 0)

array([[1.,  0.],
       [1.,  1.]])

In [ ]:
np.add.accumulate(I) # no axis specified = axis zero

array([[1.,  0.],
       [1.,  1.]])

Accumulate along axis 1 (columns), through rows:


In [ ]:
np.add.accumulate(I, 1)

array([[1.,  1.],
       [0.,  1.]])