<div class='alert alert-warning'>

NumPy's interactive examples are experimental and may not always work as expected, with high load times especially on low-resource platforms, and the version of NumPy might not be in sync with the one you are browsing the documentation for. If you encounter any issues, please report them on the [NumPy issue tracker](https://github.com/numpy/numpy/issues).

</div>

In [ ]:
import numpy as np
x = np.array([[4, 9, 2, 10],
              [6, 9, 7, 12]])

In [ ]:
np.ptp(x, axis=1)

array([8, 6])

In [ ]:
np.ptp(x, axis=0)

array([2, 0, 5, 2])

In [ ]:
np.ptp(x)

10

This example shows that a negative value can be returned when
the input is an array of signed integers.


In [ ]:
y = np.array([[1, 127],
              [0, 127],
              [-1, 127],
              [-2, 127]], dtype=np.int8)
np.ptp(y, axis=1)

array([ 126,  127, -128, -127], dtype=int8)

A work-around is to use the `view()` method to view the result as
unsigned integers with the same bit width:


In [ ]:
np.ptp(y, axis=1).view(np.uint8)

array([126, 127, 128, 129], dtype=uint8)