<div class='alert alert-warning'>

NumPy's interactive examples are experimental and may not always work as expected, with high load times especially on low-resource platforms, , and the version of NumPy might not be in sync with the one you are browsing the documentation for. If you encounter any issues, please report them on the [NumPy issue tracker](https://github.com/numpy/numpy/issues).

</div>

In [ ]:
from numpy.polynomial import chebyshev as C
c = (1,2,3)
C.chebint(c)

array([ 0.5, -0.5,  0.5,  0.5])

In [ ]:
C.chebint(c,3)

array([ 0.03125   , -0.1875    ,  0.04166667, -0.05208333,  0.01041667, # may vary
    0.00625   ])

In [ ]:
C.chebint(c, k=3)

array([ 3.5, -0.5,  0.5,  0.5])

In [ ]:
C.chebint(c,lbnd=-2)

array([ 8.5, -0.5,  0.5,  0.5])

In [ ]:
C.chebint(c,scl=-2)

array([-1.,  1., -1., -1.])