<div class='alert alert-warning'>

NumPy's interactive examples are experimental and may not always work as expected, with high load times especially on low-resource platforms, and the version of NumPy might not be in sync with the one you are browsing the documentation for. If you encounter any issues, please report them on the [NumPy issue tracker](https://github.com/numpy/numpy/issues).

</div>

In [ ]:
import numpy as np
A = np.array([[1,-2j],[2j,5]])
A

array([[ 1.+0.j, -0.-2.j],
       [ 0.+2.j,  5.+0.j]])

In [ ]:
L = np.linalg.cholesky(A)
L

array([[1.+0.j, 0.+0.j],
       [0.+2.j, 1.+0.j]])

In [ ]:
np.dot(L, L.T.conj()) # verify that L * L.H = A

array([[1.+0.j, 0.-2.j],
       [0.+2.j, 5.+0.j]])

In [ ]:
A = [[1,-2j],[2j,5]] # what happens if A is only array_like?
np.linalg.cholesky(A) # an ndarray object is returned

array([[1.+0.j, 0.+0.j],
       [0.+2.j, 1.+0.j]])

In [ ]:
# But a matrix object is returned if A is a matrix object
np.linalg.cholesky(np.matrix(A))

matrix([[ 1.+0.j,  0.+0.j],
        [ 0.+2.j,  1.+0.j]])

In [ ]:
# The upper-triangular Cholesky factor can also be obtained.
np.linalg.cholesky(A, upper=True)

array([[1.-0.j, 0.-2.j],
       [0.-0.j, 1.-0.j]])