<div class='alert alert-warning'>

NumPy's interactive examples are experimental and may not always work as expected, with high load times especially on low-resource platforms, , and the version of NumPy might not be in sync with the one you are browsing the documentation for. If you encounter any issues, please report them on the [NumPy issue tracker](https://github.com/numpy/numpy/issues).

</div>

In [ ]:
import numpy as np
np.fmod([-3, -2, -1, 1, 2, 3], 2)

array([-1,  0, -1,  1,  0,  1])

In [ ]:
np.remainder([-3, -2, -1, 1, 2, 3], 2)

array([1, 0, 1, 1, 0, 1])

In [ ]:
np.fmod([5, 3], [2, 2.])

array([ 1.,  1.])

In [ ]:
a = np.arange(-3, 3).reshape(3, 2)
a

array([[-3, -2],
       [-1,  0],
       [ 1,  2]])

In [ ]:
np.fmod(a, [2,2])

array([[-1,  0],
       [-1,  0],
       [ 1,  0]])