<div class='alert alert-warning'>

NumPy's interactive examples are experimental and may not always work as expected, with high load times especially on low-resource platforms, and the version of NumPy might not be in sync with the one you are browsing the documentation for. If you encounter any issues, please report them on the [NumPy issue tracker](https://github.com/numpy/numpy/issues).

</div>

Floating point precision can be set:


In [ ]:
import numpy as np
np.set_printoptions(precision=4)
np.array([1.123456789])

[1.1235]

Long arrays can be summarised:


In [ ]:
np.set_printoptions(threshold=5)
np.arange(10)

array([0, 1, 2, ..., 7, 8, 9])

Small results can be suppressed:


In [ ]:
eps = np.finfo(float).eps
x = np.arange(4.)
x**2 - (x + eps)**2

array([-4.9304e-32, -4.4409e-16,  0.0000e+00,  0.0000e+00])

In [ ]:
np.set_printoptions(suppress=True)
x**2 - (x + eps)**2

array([-0., -0.,  0.,  0.])

A custom formatter can be used to display array elements as desired:


In [ ]:
np.set_printoptions(formatter={'all':lambda x: 'int: '+str(-x)})
x = np.arange(3)
x

array([int: 0, int: -1, int: -2])

In [ ]:
np.set_printoptions()  # formatter gets reset
x

array([0, 1, 2])

To put back the default options, you can use:


In [ ]:
np.set_printoptions(edgeitems=3, infstr='inf',
linewidth=75, nanstr='nan', precision=8,
suppress=False, threshold=1000, formatter=None)

Also to temporarily override options, use `printoptions`
as a context manager:


In [ ]:
with np.printoptions(precision=2, suppress=True, threshold=5):
    np.linspace(0, 10, 10)

array([ 0.  ,  1.11,  2.22, ...,  7.78,  8.89, 10.  ])