<div class='alert alert-warning'>

NumPy's interactive examples are experimental and may not always work as expected, with high load times especially on low-resource platforms, , and the version of NumPy might not be in sync with the one you are browsing the documentation for. If you encounter any issues, please report them on the [NumPy issue tracker](https://github.com/numpy/numpy/issues).

</div>

In [ ]:
from numpy.polynomial import chebyshev as C
c = (1,2,3,4)
C.chebder(c)

array([14., 12., 24.])

In [ ]:
C.chebder(c,3)

array([96.])

In [ ]:
C.chebder(c,scl=-1)

array([-14., -12., -24.])

In [ ]:
C.chebder(c,2,-1)

array([12.,  96.])