<div class='alert alert-warning'>

NumPy's interactive examples are experimental and may not always work as expected, with high load times especially on low-resource platforms, , and the version of NumPy might not be in sync with the one you are browsing the documentation for. If you encounter any issues, please report them on the [NumPy issue tracker](https://github.com/numpy/numpy/issues).

</div>

In [ ]:
import numpy as np
data = np.arange(1, 5)
data

array([1, 2, 3, 4])

In [ ]:
np.average(data)

2.5

In [ ]:
np.average(np.arange(1, 11), weights=np.arange(10, 0, -1))

4.0

In [ ]:
data = np.arange(6).reshape((3, 2))
data

array([[0, 1],
       [2, 3],
       [4, 5]])

In [ ]:
np.average(data, axis=1, weights=[1./4, 3./4])

array([0.75, 2.75, 4.75])

In [ ]:
np.average(data, weights=[1./4, 3./4])

Traceback (most recent call last):
    ...
TypeError: Axis must be specified when shapes of a and weights differ.

With ``keepdims=True``, the following result has shape (3, 1).


In [ ]:
np.average(data, axis=1, keepdims=True)

array([[0.5],
       [2.5],
       [4.5]])

In [ ]:
data = np.arange(8).reshape((2, 2, 2))
data

array([[[0, 1],
        [2, 3]],
       [[4, 5],
        [6, 7]]])

In [ ]:
np.average(data, axis=(0, 1), weights=[[1./4, 3./4], [1., 1./2]])

array([3.4, 4.4])

In [ ]:
np.average(data, axis=0, weights=[[1./4, 3./4], [1., 1./2]])

Traceback (most recent call last):
    ...
ValueError: Shape of weights must be consistent
with shape of a along specified axis.