<div class='alert alert-warning'>

NumPy's interactive examples are experimental and may not always work as expected, with high load times especially on low-resource platforms, and the version of NumPy might not be in sync with the one you are browsing the documentation for. If you encounter any issues, please report them on the [NumPy issue tracker](https://github.com/numpy/numpy/issues).

</div>

In [ ]:
import numpy as np
phase = np.linspace(0, np.pi, num=5)
phase[3:] += np.pi
phase

array([ 0.        ,  0.78539816,  1.57079633,  5.49778714,  6.28318531]) # may vary

In [ ]:
np.unwrap(phase)

array([ 0.        ,  0.78539816,  1.57079633, -0.78539816,  0.        ]) # may vary

In [ ]:
np.unwrap([0, 1, 2, -1, 0], period=4)

array([0, 1, 2, 3, 4])

In [ ]:
np.unwrap([ 1, 2, 3, 4, 5, 6, 1, 2, 3], period=6)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.unwrap([2, 3, 4, 5, 2, 3, 4, 5], period=4)

array([2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
phase_deg = np.mod(np.linspace(0 ,720, 19), 360) - 180
np.unwrap(phase_deg, period=360)

array([-180., -140., -100.,  -60.,  -20.,   20.,   60.,  100.,  140.,
        180.,  220.,  260.,  300.,  340.,  380.,  420.,  460.,  500.,
        540.])