<div class='alert alert-warning'>

NumPy's interactive examples are experimental and may not always work as expected, with high load times especially on low-resource platforms, and the version of NumPy might not be in sync with the one you are browsing the documentation for. If you encounter any issues, please report them on the [NumPy issue tracker](https://github.com/numpy/numpy/issues).

</div>

In [ ]:
import numpy as np
np.sum([0.5, 1.5])

2.0

In [ ]:
np.sum([0.5, 0.7, 0.2, 1.5], dtype=np.int32)

1

In [ ]:
np.sum([[0, 1], [0, 5]])

6

In [ ]:
np.sum([[0, 1], [0, 5]], axis=0)

array([0, 6])

In [ ]:
np.sum([[0, 1], [0, 5]], axis=1)

array([1, 5])

In [ ]:
np.sum([[0, 1], [np.nan, 5]], where=[False, True], axis=1)

array([1., 5.])

If the accumulator is too small, overflow occurs:


In [ ]:
np.ones(128, dtype=np.int8).sum(dtype=np.int8)

-128

You can also start the sum with a value other than zero:


In [ ]:
np.sum([10], initial=5)

15