<div class='alert alert-warning'>

NumPy's interactive examples are experimental and may not always work as expected, with high load times especially on low-resource platforms, , and the version of NumPy might not be in sync with the one you are browsing the documentation for. If you encounter any issues, please report them on the [NumPy issue tracker](https://github.com/numpy/numpy/issues).

</div>

In [ ]:
import numpy as np
arr = np.array([[3,6,6],[4,5,1]])
np.ravel_multi_index(arr, (7,6))

array([22, 41, 37])

In [ ]:
np.ravel_multi_index(arr, (7,6), order='F')

array([31, 41, 13])

In [ ]:
np.ravel_multi_index(arr, (4,6), mode='clip')

array([22, 23, 19])

In [ ]:
np.ravel_multi_index(arr, (4,4), mode=('clip','wrap'))

array([12, 13, 13])

In [ ]:
np.ravel_multi_index((3,1,4,1), (6,7,8,9))

1621