<div class='alert alert-warning'>

NumPy's interactive examples are experimental and may not always work as expected, with high load times especially on low-resource platforms, , and the version of NumPy might not be in sync with the one you are browsing the documentation for. If you encounter any issues, please report them on the [NumPy issue tracker](https://github.com/numpy/numpy/issues).

</div>

In [ ]:
import numpy as np
x = np.arange(6)
x = x.reshape((2, 3))
x

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
np.ones_like(x)

array([[1, 1, 1],
       [1, 1, 1]])

In [ ]:
y = np.arange(3, dtype=float)
y

array([0., 1., 2.])

In [ ]:
np.ones_like(y)

array([1.,  1.,  1.])