<div class='alert alert-warning'>

NumPy's interactive examples are experimental and may not always work as expected, with high load times especially on low-resource platforms, and the version of NumPy might not be in sync with the one you are browsing the documentation for. If you encounter any issues, please report them on the [NumPy issue tracker](https://github.com/numpy/numpy/issues).

</div>

In [ ]:
import numpy as np
from numpy import linalg as LA
a = np.arange(9) - 4
a

array([-4, -3, -2, ...,  2,  3,  4])

In [ ]:
b = a.reshape((3, 3))
b

array([[-4, -3, -2],
       [-1,  0,  1],
       [ 2,  3,  4]])

In [ ]:
LA.norm(a)

7.745966692414834

In [ ]:
LA.norm(b)

7.745966692414834

In [ ]:
LA.norm(b, 'fro')

7.745966692414834

In [ ]:
LA.norm(a, np.inf)

4.0

In [ ]:
LA.norm(b, np.inf)

9.0

In [ ]:
LA.norm(a, -np.inf)

0.0

In [ ]:
LA.norm(b, -np.inf)

2.0

In [ ]:
LA.norm(a, 1)

20.0

In [ ]:
LA.norm(b, 1)

7.0

In [ ]:
LA.norm(a, -1)

-4.6566128774142013e-010

In [ ]:
LA.norm(b, -1)

6.0

In [ ]:
LA.norm(a, 2)

7.745966692414834

In [ ]:
LA.norm(b, 2)

7.3484692283495345

In [ ]:
LA.norm(a, -2)

0.0

In [ ]:
LA.norm(b, -2)

1.8570331885190563e-016 # may vary

In [ ]:
LA.norm(a, 3)

5.8480354764257312 # may vary

In [ ]:
LA.norm(a, -3)

0.0

Using the `axis` argument to compute vector norms:


In [ ]:
c = np.array([[ 1, 2, 3],
              [-1, 1, 4]])
LA.norm(c, axis=0)

array([ 1.41421356,  2.23606798,  5.        ])

In [ ]:
LA.norm(c, axis=1)

array([ 3.74165739,  4.24264069])

In [ ]:
LA.norm(c, ord=1, axis=1)

array([ 6.,  6.])

Using the `axis` argument to compute matrix norms:


In [ ]:
m = np.arange(8).reshape(2,2,2)
LA.norm(m, axis=(1,2))

array([  3.74165739,  11.22497216])

In [ ]:
LA.norm(m[0, :, :]), LA.norm(m[1, :, :])

(3.7416573867739413, 11.224972160321824)