<div class='alert alert-warning'>

NumPy's interactive examples are experimental and may not always work as expected, with high load times especially on low-resource platforms, , and the version of NumPy might not be in sync with the one you are browsing the documentation for. If you encounter any issues, please report them on the [NumPy issue tracker](https://github.com/numpy/numpy/issues).

</div>

In [ ]:
import numpy as np
np.remainder([4, 7], [2, 3])

array([0, 1])

In [ ]:
np.remainder(np.arange(7), 5)

array([0, 1, 2, 3, 4, 0, 1])

The ``%`` operator can be used as a shorthand for ``np.remainder`` on
ndarrays.


In [ ]:
x1 = np.arange(7)
x1 % 5

array([0, 1, 2, 3, 4, 0, 1])