<div class='alert alert-warning'>

NumPy's interactive examples are experimental and may not always work as expected, with high load times especially on low-resource platforms, , and the version of NumPy might not be in sync with the one you are browsing the documentation for. If you encounter any issues, please report them on the [NumPy issue tracker](https://github.com/numpy/numpy/issues).

</div>

In [ ]:
import numpy as np

The number 13 is represented by ``00001101``. Likewise, 17 is
represented by ``00010001``.  The bit-wise XOR of 13 and 17 is
therefore ``00011100``, or 28:


In [ ]:
np.bitwise_xor(13, 17)

28

In [ ]:
np.binary_repr(28)

'11100'

In [ ]:
np.bitwise_xor(31, 5)

26

In [ ]:
np.bitwise_xor([31,3], 5)

array([26,  6])

In [ ]:
np.bitwise_xor([31,3], [5,6])

array([26,  5])

In [ ]:
np.bitwise_xor([True, True], [False, True])

array([ True, False])

The ``^`` operator can be used as a shorthand for ``np.bitwise_xor`` on
ndarrays.


In [ ]:
x1 = np.array([True, True])
x2 = np.array([False, True])
x1 ^ x2

array([ True, False])