<div class='alert alert-warning'>

NumPy's interactive examples are experimental and may not always work as expected, with high load times especially on low-resource platforms, and the version of NumPy might not be in sync with the one you are browsing the documentation for. If you encounter any issues, please report them on the [NumPy issue tracker](https://github.com/numpy/numpy/issues).

</div>

In [ ]:
a = np.array([1, 2, 3])
np.cumulative_prod(a)  # intermediate results 1, 1*2
                       # total product 1*2*3 = 6

array([1, 2, 6])

In [ ]:
a = np.array([1, 2, 3, 4, 5, 6])
np.cumulative_prod(a, dtype=float) # specify type of output

array([   1.,    2.,    6.,   24.,  120.,  720.])

The cumulative product for each column (i.e., over the rows) of ``b``:


In [ ]:
b = np.array([[1, 2, 3], [4, 5, 6]])
np.cumulative_prod(b, axis=0)

array([[ 1,  2,  3],
       [ 4, 10, 18]])

The cumulative product for each row (i.e. over the columns) of ``b``:


In [ ]:
np.cumulative_prod(b, axis=1)

array([[  1,   2,   6],
       [  4,  20, 120]])