<div class='alert alert-warning'>

NumPy's interactive examples are experimental and may not always work as expected, with high load times especially on low-resource platforms, , and the version of NumPy might not be in sync with the one you are browsing the documentation for. If you encounter any issues, please report them on the [NumPy issue tracker](https://github.com/numpy/numpy/issues).

</div>

In [ ]:
import numpy as np
arr = np.array([0, 0, 0, 1, 2, 3, 3, 4, 5])
np.histogram_bin_edges(arr, bins='auto', range=(0, 1))

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [ ]:
np.histogram_bin_edges(arr, bins=2)

array([0. , 2.5, 5. ])

For consistency with histogram, an array of pre-computed bins is
passed through unmodified:


In [ ]:
np.histogram_bin_edges(arr, [1, 2])

array([1, 2])

This function allows one set of bins to be computed, and reused across
multiple histograms:


In [ ]:
shared_bins = np.histogram_bin_edges(arr, bins='auto')
shared_bins

array([0., 1., 2., 3., 4., 5.])

In [ ]:
group_id = np.array([0, 1, 1, 0, 1, 1, 0, 1, 1])
hist_0, _ = np.histogram(arr[group_id == 0], bins=shared_bins)
hist_1, _ = np.histogram(arr[group_id == 1], bins=shared_bins)

In [ ]:
hist_0; hist_1

array([1, 1, 0, 1, 0])
array([2, 0, 1, 1, 2])

Which gives more easily comparable results than using separate bins for
each histogram:


In [ ]:
hist_0, bins_0 = np.histogram(arr[group_id == 0], bins='auto')
hist_1, bins_1 = np.histogram(arr[group_id == 1], bins='auto')
hist_0; hist_1

array([1, 1, 1])
array([2, 1, 1, 2])

In [ ]:
bins_0; bins_1

array([0., 1., 2., 3.])
array([0.  , 1.25, 2.5 , 3.75, 5.  ])