<div class='alert alert-warning'>

NumPy's interactive examples are experimental and may not always work as expected, with high load times especially on low-resource platforms, and the version of NumPy might not be in sync with the one you are browsing the documentation for. If you encounter any issues, please report them on the [NumPy issue tracker](https://github.com/numpy/numpy/issues).

</div>

In [ ]:
import numpy as np
def myfunc(a, b):
    "Return a-b if a>b, otherwise return a+b"
    if a > b:
        return a - b
    else:
        return a + b

In [ ]:
vfunc = np.vectorize(myfunc)
vfunc([1, 2, 3, 4], 2)

array([3, 4, 1, 2])

The docstring is taken from the input function to `vectorize` unless it
is specified:


In [ ]:
vfunc.__doc__

'Return a-b if a>b, otherwise return a+b'

In [ ]:
vfunc = np.vectorize(myfunc, doc='Vectorized `myfunc`')
vfunc.__doc__

'Vectorized `myfunc`'

The output type is determined by evaluating the first element of the input,
unless it is specified:


In [ ]:
out = vfunc([1, 2, 3, 4], 2)
type(out[0])

<class 'numpy.int64'>

In [ ]:
vfunc = np.vectorize(myfunc, otypes=[float])
out = vfunc([1, 2, 3, 4], 2)
type(out[0])

<class 'numpy.float64'>

The `excluded` argument can be used to prevent vectorizing over certain
arguments.  This can be useful for array-like arguments of a fixed length
such as the coefficients for a polynomial as in `polyval`:


In [ ]:
def mypolyval(p, x):
    _p = list(p)
    res = _p.pop(0)
    while _p:
        res = res*x + _p.pop(0)
    return res
vpolyval = np.vectorize(mypolyval, excluded=['p'])
vpolyval(p=[1, 2, 3], x=[0, 1])

array([3, 6])

Positional arguments may also be excluded by specifying their position:


In [ ]:
vpolyval.excluded.add(0)
vpolyval([1, 2, 3], x=[0, 1])

array([3, 6])

The `signature` argument allows for vectorizing functions that act on
non-scalar arrays of fixed length. For example, you can use it for a
vectorized calculation of Pearson correlation coefficient and its p-value:


In [ ]:
import scipy.stats
pearsonr = np.vectorize(scipy.stats.pearsonr,
                signature='(n),(n)->(),()')
pearsonr([[0, 1, 2, 3]], [[1, 2, 3, 4], [4, 3, 2, 1]])

(array([ 1., -1.]), array([ 0.,  0.]))

Or for a vectorized convolution:


In [ ]:
convolve = np.vectorize(np.convolve, signature='(n),(m)->(k)')
convolve(np.eye(4), [1, 2, 1])

array([[1., 2., 1., 0., 0., 0.],
       [0., 1., 2., 1., 0., 0.],
       [0., 0., 1., 2., 1., 0.],
       [0., 0., 0., 1., 2., 1.]])

Decorator syntax is supported.  The decorator can be called as
a function to provide keyword arguments:


In [ ]:
@np.vectorize
def identity(x):
    return x

identity([0, 1, 2])

array([0, 1, 2])

In [ ]:
@np.vectorize(otypes=[float])
def as_float(x):
    return x

as_float([0, 1, 2])

array([0., 1., 2.])