<div class='alert alert-warning'>

NumPy's interactive examples are experimental and may not always work as expected, with high load times especially on low-resource platforms, , and the version of NumPy might not be in sync with the one you are browsing the documentation for. If you encounter any issues, please report them on the [NumPy issue tracker](https://github.com/numpy/numpy/issues).

</div>

In [ ]:
x = np.matrix(np.arange(12).reshape((3, 4)))
x

matrix([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [ ]:
x.mean()

5.5

In [ ]:
x.mean(0)

matrix([[4., 5., 6., 7.]])

In [ ]:
x.mean(1)

matrix([[ 1.5],
        [ 5.5],
        [ 9.5]])