<div class='alert alert-warning'>

NumPy's interactive examples are experimental and may not always work as expected, with high load times especially on low-resource platforms, and the version of NumPy might not be in sync with the one you are browsing the documentation for. If you encounter any issues, please report them on the [NumPy issue tracker](https://github.com/numpy/numpy/issues).

</div>

In [ ]:
import numpy as np
A = np.array([1, 256, 8755], dtype=np.int16)
list(map(hex, A))

['0x1', '0x100', '0x2233']

In [ ]:
A.byteswap(inplace=True)

array([  256,     1, 13090], dtype=int16)

In [ ]:
list(map(hex, A))

['0x100', '0x1', '0x3322']

Arrays of byte-strings are not swapped


In [ ]:
A = np.array([b'ceg', b'fac'])
A.byteswap()

array([b'ceg', b'fac'], dtype='|S3')

``A.view(A.dtype.newbyteorder()).byteswap()`` produces an array with
the same values but different representation in memory


In [ ]:
A = np.array([1, 2, 3],dtype=np.int64)
A.view(np.uint8)

array([1, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 0,
       0, 0], dtype=uint8)

In [ ]:
A.view(A.dtype.newbyteorder()).byteswap(inplace=True)

array([1, 2, 3], dtype='>i8')

In [ ]:
A.view(np.uint8)

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0,
       0, 3], dtype=uint8)