<div class='alert alert-warning'>

NumPy's interactive examples are experimental and may not always work as expected, with high load times especially on low-resource platforms, , and the version of NumPy might not be in sync with the one you are browsing the documentation for. If you encounter any issues, please report them on the [NumPy issue tracker](https://github.com/numpy/numpy/issues).

</div>

In [ ]:
import numpy as np
np.sqrt([1,4,9])

array([ 1.,  2.,  3.])

In [ ]:
np.sqrt([4, -1, -3+4J])

array([ 2.+0.j,  0.+1.j,  1.+2.j])

In [ ]:
np.sqrt([4, -1, np.inf])

array([ 2., nan, inf])