<div class='alert alert-warning'>

NumPy's interactive examples are experimental and may not always work as expected, with high load times especially on low-resource platforms, and the version of NumPy might not be in sync with the one you are browsing the documentation for. If you encounter any issues, please report them on the [NumPy issue tracker](https://github.com/numpy/numpy/issues).

</div>

In [ ]:
a = np.array([1, 2, 3, 4, 5, 6])
a

array([1, 2, 3, 4, 5, 6])

In [ ]:
np.cumulative_sum(a)

array([ 1,  3,  6, 10, 15, 21])

In [ ]:
np.cumulative_sum(a, dtype=float)  # specifies type of output value(s)

array([  1.,   3.,   6.,  10.,  15.,  21.])

In [ ]:
b = np.array([[1, 2, 3], [4, 5, 6]])
np.cumulative_sum(b,axis=0)  # sum over rows for each of the 3 columns

array([[1, 2, 3],
       [5, 7, 9]])

In [ ]:
np.cumulative_sum(b,axis=1)  # sum over columns for each of the 2 rows

array([[ 1,  3,  6],
       [ 4,  9, 15]])

``cumulative_sum(c)[-1]`` may not be equal to ``sum(c)``


In [ ]:
c = np.array([1, 2e-9, 3e-9] * 1000000)
np.cumulative_sum(c)[-1]

1000000.0050045159

In [ ]:
c.sum()

1000000.0050000029