<div class='alert alert-warning'>

NumPy's interactive examples are experimental and may not always work as expected, with high load times especially on low-resource platforms, and the version of NumPy might not be in sync with the one you are browsing the documentation for. If you encounter any issues, please report them on the [NumPy issue tracker](https://github.com/numpy/numpy/issues).

</div>

In [ ]:
import numpy as np
x = np.array([1, 2])
x.shape

(2,)

The following is equivalent to ``x[np.newaxis, :]`` or ``x[np.newaxis]``:


In [ ]:
y = np.expand_dims(x, axis=0)
y

array([[1, 2]])

In [ ]:
y.shape

(1, 2)

The following is equivalent to ``x[:, np.newaxis]``:


In [ ]:
y = np.expand_dims(x, axis=1)
y

array([[1],
       [2]])

In [ ]:
y.shape

(2, 1)

``axis`` may also be a tuple:


In [ ]:
y = np.expand_dims(x, axis=(0, 1))
y

array([[[1, 2]]])

In [ ]:
y = np.expand_dims(x, axis=(2, 0))
y

array([[[1],
        [2]]])

Note that some examples may use ``None`` instead of ``np.newaxis``.  These
are the same objects:


In [ ]:
np.newaxis is None

True