<div class='alert alert-warning'>

NumPy's interactive examples are experimental and may not always work as expected, with high load times especially on low-resource platforms, and the version of NumPy might not be in sync with the one you are browsing the documentation for. If you encounter any issues, please report them on the [NumPy issue tracker](https://github.com/numpy/numpy/issues).

</div>

In [ ]:
import numpy as np

Consider two variables, $x_0$ and $x_1$, which
correlate perfectly, but in opposite directions:


In [ ]:
x = np.array([[0, 2], [1, 1], [2, 0]]).T
x

array([[0, 1, 2],
       [2, 1, 0]])

Note how $x_0$ increases while $x_1$ decreases. The covariance
matrix shows this clearly:


In [ ]:
np.cov(x)

array([[ 1., -1.],
       [-1.,  1.]])

Note that element $C_{0,1}$, which shows the correlation between
$x_0$ and $x_1$, is negative.

Further, note how `x` and `y` are combined:


In [ ]:
x = [-2.1, -1,  4.3]
y = [3,  1.1,  0.12]
X = np.stack((x, y), axis=0)
np.cov(X)

array([[11.71      , -4.286     ], # may vary
       [-4.286     ,  2.144133]])

In [ ]:
np.cov(x, y)

array([[11.71      , -4.286     ], # may vary
       [-4.286     ,  2.144133]])

In [ ]:
np.cov(x)

array(11.71)