<div class='alert alert-warning'>

NumPy's interactive examples are experimental and may not always work as expected, with high load times especially on low-resource platforms, and the version of NumPy might not be in sync with the one you are browsing the documentation for. If you encounter any issues, please report them on the [NumPy issue tracker](https://github.com/numpy/numpy/issues).

</div>

In [ ]:
import numpy as np
x = np.array([[1,2,3],[4,5,6]], order='F')

In [ ]:
y = x.copy()

In [ ]:
x.fill(0)

In [ ]:
x

array([[0, 0, 0],
       [0, 0, 0]])

In [ ]:
y

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
y.flags['C_CONTIGUOUS']

True

For arrays containing Python objects (e.g. dtype=object),
the copy is a shallow one. The new array will contain the
same object which may lead to surprises if that object can
be modified (is mutable):


In [ ]:
a = np.array([1, 'm', [2, 3, 4]], dtype=object)
b = a.copy()
b[2][0] = 10
a

array([1, 'm', list([10, 3, 4])], dtype=object)

To ensure all elements within an ``object`` array are copied,
use `copy.deepcopy`:


In [ ]:
import copy
a = np.array([1, 'm', [2, 3, 4]], dtype=object)
c = copy.deepcopy(a)
c[2][0] = 10
c

array([1, 'm', list([10, 3, 4])], dtype=object)

In [ ]:
a

array([1, 'm', list([2, 3, 4])], dtype=object)