<div class='alert alert-warning'>

NumPy's interactive examples are experimental and may not always work as expected, with high load times especially on low-resource platforms, , and the version of NumPy might not be in sync with the one you are browsing the documentation for. If you encounter any issues, please report them on the [NumPy issue tracker](https://github.com/numpy/numpy/issues).

</div>

In [ ]:
import numpy as np

The 2-D pseudo-Vandermonde matrix of degree ``[1, 2]`` and sample
points ``x = [-1, 2]`` and ``y = [1, 3]`` is as follows:


In [ ]:
from numpy.polynomial import polynomial as P
x = np.array([-1, 2])
y = np.array([1, 3])
m, n = 1, 2
deg = np.array([m, n])
V = P.polyvander2d(x=x, y=y, deg=deg)
V

array([[ 1.,  1.,  1., -1., -1., -1.],
       [ 1.,  3.,  9.,  2.,  6., 18.]])

We can verify the columns for any ``0 <= i <= m`` and ``0 <= j <= n``:


In [ ]:
i, j = 0, 1
V[:, (deg[1]+1)*i + j] == x**i * y**j

array([ True,  True])

The (1D) Vandermonde matrix of sample points ``x`` and degree ``m`` is a
special case of the (2D) pseudo-Vandermonde matrix with ``y`` points all
zero and degree ``[m, 0]``.


In [ ]:
P.polyvander2d(x=x, y=0*x, deg=(m, 0)) == P.polyvander(x=x, deg=m)

array([[ True,  True],
       [ True,  True]])