<div class='alert alert-warning'>

NumPy's interactive examples are experimental and may not always work as expected, with high load times especially on low-resource platforms, and the version of NumPy might not be in sync with the one you are browsing the documentation for. If you encounter any issues, please report them on the [NumPy issue tracker](https://github.com/numpy/numpy/issues).

</div>

For 2-D arrays it is the matrix product:


In [ ]:
import numpy as np
a = np.array([[1, 0],
              [0, 1]])
b = np.array([[4, 1],
              [2, 2]])
np.matmul(a, b)

array([[4, 1],
       [2, 2]])

For 2-D mixed with 1-D, the result is the usual.


In [ ]:
a = np.array([[1, 0],
              [0, 1]])
b = np.array([1, 2])
np.matmul(a, b)

array([1, 2])

In [ ]:
np.matmul(b, a)

array([1, 2])

Broadcasting is conventional for stacks of arrays


In [ ]:
a = np.arange(2 * 2 * 4).reshape((2, 2, 4))
b = np.arange(2 * 2 * 4).reshape((2, 4, 2))
np.matmul(a,b).shape

(2, 2, 2)

In [ ]:
np.matmul(a, b)[0, 1, 1]

98

In [ ]:
sum(a[0, 1, :] * b[0 , :, 1])

98

Vector, vector returns the scalar inner product, but neither argument
is complex-conjugated:


In [ ]:
np.matmul([2j, 3j], [2j, 3j])

(-13+0j)

Scalar multiplication raises an error.


In [ ]:
np.matmul([1,2], 3)


Traceback (most recent call last):
ValueError: matmul: Input operand 1 does not have enough dimensions ...

The ``@`` operator can be used as a shorthand for ``np.matmul`` on
ndarrays.


In [ ]:
x1 = np.array([2j, 3j])
x2 = np.array([2j, 3j])
x1 @ x2

(-13+0j)

.. versionadded:: 1.10.0