<div class='alert alert-warning'>

NumPy's interactive examples are experimental and may not always work as expected, with high load times especially on low-resource platforms, and the version of NumPy might not be in sync with the one you are browsing the documentation for. If you encounter any issues, please report them on the [NumPy issue tracker](https://github.com/numpy/numpy/issues).

</div>

In [ ]:
import numpy as np

Construct the polynomial $x^2 + 2x + 3$:


In [ ]:
import numpy as np

In [ ]:
p = np.poly1d([1, 2, 3])
print(np.poly1d(p))

   2
1 x + 2 x + 3

Evaluate the polynomial at $x = 0.5$:


In [ ]:
p(0.5)

4.25

Find the roots:


In [ ]:
p.r

array([-1.+1.41421356j, -1.-1.41421356j])

In [ ]:
p(p.r)

array([ -4.44089210e-16+0.j,  -4.44089210e-16+0.j]) # may vary

These numbers in the previous line represent (0, 0) to machine precision

Show the coefficients:


In [ ]:
p.c

array([1, 2, 3])

Display the order (the leading zero-coefficients are removed):


In [ ]:
p.order

2

Show the coefficient of the k-th power in the polynomial
(which is equivalent to ``p.c[-(i+1)]``):


In [ ]:
p[1]

2

Polynomials can be added, subtracted, multiplied, and divided
(returns quotient and remainder):


In [ ]:
p * p

poly1d([ 1,  4, 10, 12,  9])

In [ ]:
(p**3 + 4) / p

(poly1d([ 1.,  4., 10., 12.,  9.]), poly1d([4.]))

``asarray(p)`` gives the coefficient array, so polynomials can be
used in all functions that accept arrays:


In [ ]:
p**2 # square of polynomial

poly1d([ 1,  4, 10, 12,  9])

In [ ]:
np.square(p) # square of individual coefficients

array([1, 4, 9])

The variable used in the string representation of `p` can be modified,
using the `variable` parameter:


In [ ]:
p = np.poly1d([1,2,3], variable='z')
print(p)

   2
1 z + 2 z + 3

Construct a polynomial from its roots:


In [ ]:
np.poly1d([1, 2], True)

poly1d([ 1., -3.,  2.])

This is the same polynomial as obtained by:


In [ ]:
np.poly1d([1, -1]) * np.poly1d([1, -2])

poly1d([ 1, -3,  2])