<div class='alert alert-warning'>

NumPy's interactive examples are experimental and may not always work as expected, with high load times especially on low-resource platforms, , and the version of NumPy might not be in sync with the one you are browsing the documentation for. If you encounter any issues, please report them on the [NumPy issue tracker](https://github.com/numpy/numpy/issues).

</div>

In [ ]:
import numpy as np

For this sample array


In [ ]:
a = np.array([[10, 30, 20], [60, 40, 50]])

We can sort either by using sort directly, or argsort and this function


In [ ]:
np.sort(a, axis=1)

array([[10, 20, 30],
       [40, 50, 60]])

In [ ]:
ai = np.argsort(a, axis=1)
ai

array([[0, 2, 1],
       [1, 2, 0]])

In [ ]:
np.take_along_axis(a, ai, axis=1)

array([[10, 20, 30],
       [40, 50, 60]])

The same works for max and min, if you maintain the trivial dimension
with ``keepdims``:


In [ ]:
np.max(a, axis=1, keepdims=True)

array([[30],
       [60]])

In [ ]:
ai = np.argmax(a, axis=1, keepdims=True)
ai

array([[1],
       [0]])

In [ ]:
np.take_along_axis(a, ai, axis=1)

array([[30],
       [60]])

If we want to get the max and min at the same time, we can stack the
indices first


In [ ]:
ai_min = np.argmin(a, axis=1, keepdims=True)
ai_max = np.argmax(a, axis=1, keepdims=True)
ai = np.concatenate([ai_min, ai_max], axis=1)
ai

array([[0, 1],
       [1, 0]])

In [ ]:
np.take_along_axis(a, ai, axis=1)

array([[10, 30],
       [40, 60]])