<div class='alert alert-warning'>

NumPy's interactive examples are experimental and may not always work as expected, with high load times especially on low-resource platforms, and the version of NumPy might not be in sync with the one you are browsing the documentation for. If you encounter any issues, please report them on the [NumPy issue tracker](https://github.com/numpy/numpy/issues).

</div>

Vector cross-product.


In [ ]:
import numpy as np
x = [1, 2, 3]
y = [4, 5, 6]
np.cross(x, y)

array([-3,  6, -3])

One vector with dimension 2.


In [ ]:
x = [1, 2]
y = [4, 5, 6]
np.cross(x, y)

array([12, -6, -3])

Equivalently:


In [ ]:
x = [1, 2, 0]
y = [4, 5, 6]
np.cross(x, y)

array([12, -6, -3])

Both vectors with dimension 2.


In [ ]:
x = [1,2]
y = [4,5]
np.cross(x, y)

array(-3)

Multiple vector cross-products. Note that the direction of the cross
product vector is defined by the *right-hand rule*.


In [ ]:
x = np.array([[1,2,3], [4,5,6]])
y = np.array([[4,5,6], [1,2,3]])
np.cross(x, y)

array([[-3,  6, -3],
       [ 3, -6,  3]])

The orientation of `c` can be changed using the `axisc` keyword.


In [ ]:
np.cross(x, y, axisc=0)

array([[-3,  3],
       [ 6, -6],
       [-3,  3]])

Change the vector definition of `x` and `y` using `axisa` and `axisb`.


In [ ]:
x = np.array([[1,2,3], [4,5,6], [7, 8, 9]])
y = np.array([[7, 8, 9], [4,5,6], [1,2,3]])
np.cross(x, y)

array([[ -6,  12,  -6],
       [  0,   0,   0],
       [  6, -12,   6]])

In [ ]:
np.cross(x, y, axisa=0, axisb=0)

array([[-24,  48, -24],
       [-30,  60, -30],
       [-36,  72, -36]])