<div class='alert alert-warning'>

NumPy's interactive examples are experimental and may not always work as expected, with high load times especially on low-resource platforms, , and the version of NumPy might not be in sync with the one you are browsing the documentation for. If you encounter any issues, please report them on the [NumPy issue tracker](https://github.com/numpy/numpy/issues).

</div>

In [ ]:
import numpy as np
a = np.array([[10., 7., 4.], [3., 2., 1.]])
a[0][1] = np.nan
a

array([[10.,  nan,   4.],
      [ 3.,   2.,   1.]])

In [ ]:
np.quantile(a, 0.5)

np.float64(nan)

In [ ]:
np.nanquantile(a, 0.5)

3.0

In [ ]:
np.nanquantile(a, 0.5, axis=0)

array([6.5, 2. , 2.5])

In [ ]:
np.nanquantile(a, 0.5, axis=1, keepdims=True)

array([[7.],
       [2.]])

In [ ]:
m = np.nanquantile(a, 0.5, axis=0)
out = np.zeros_like(m)
np.nanquantile(a, 0.5, axis=0, out=out)

array([6.5, 2. , 2.5])

In [ ]:
m

array([6.5,  2. ,  2.5])

In [ ]:
b = a.copy()
np.nanquantile(b, 0.5, axis=1, overwrite_input=True)

array([7., 2.])

In [ ]:
assert not np.all(a==b)