<div class='alert alert-warning'>

NumPy's interactive examples are experimental and may not always work as expected, with high load times especially on low-resource platforms, , and the version of NumPy might not be in sync with the one you are browsing the documentation for. If you encounter any issues, please report them on the [NumPy issue tracker](https://github.com/numpy/numpy/issues).

</div>

In [ ]:
import numpy as np
x = np.arange(10)
np.roll(x, 2)

array([8, 9, 0, 1, 2, 3, 4, 5, 6, 7])

In [ ]:
np.roll(x, -2)

array([2, 3, 4, 5, 6, 7, 8, 9, 0, 1])

In [ ]:
x2 = np.reshape(x, (2, 5))
x2

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [ ]:
np.roll(x2, 1)

array([[9, 0, 1, 2, 3],
       [4, 5, 6, 7, 8]])

In [ ]:
np.roll(x2, -1)

array([[1, 2, 3, 4, 5],
       [6, 7, 8, 9, 0]])

In [ ]:
np.roll(x2, 1, axis=0)

array([[5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4]])

In [ ]:
np.roll(x2, -1, axis=0)

array([[5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4]])

In [ ]:
np.roll(x2, 1, axis=1)

array([[4, 0, 1, 2, 3],
       [9, 5, 6, 7, 8]])

In [ ]:
np.roll(x2, -1, axis=1)

array([[1, 2, 3, 4, 0],
       [6, 7, 8, 9, 5]])

In [ ]:
np.roll(x2, (1, 1), axis=(1, 0))

array([[9, 5, 6, 7, 8],
       [4, 0, 1, 2, 3]])

In [ ]:
np.roll(x2, (2, 1), axis=(1, 0))

array([[8, 9, 5, 6, 7],
       [3, 4, 0, 1, 2]])