<div class='alert alert-warning'>

NumPy's interactive examples are experimental and may not always work as expected, with high load times especially on low-resource platforms, , and the version of NumPy might not be in sync with the one you are browsing the documentation for. If you encounter any issues, please report them on the [NumPy issue tracker](https://github.com/numpy/numpy/issues).

</div>

In [ ]:
import numpy as np
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])
np.concatenate((a, b), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
np.concatenate((a, b.T), axis=1)

array([[1, 2, 5],
       [3, 4, 6]])

In [ ]:
np.concatenate((a, b), axis=None)

array([1, 2, 3, 4, 5, 6])

This function will not preserve masking of MaskedArray inputs.


In [ ]:
a = np.ma.arange(3)
a[1] = np.ma.masked
b = np.arange(2, 5)
a

masked_array(data=[0, --, 2],
             mask=[False,  True, False],
       fill_value=999999)

In [ ]:
b

array([2, 3, 4])

In [ ]:
np.concatenate([a, b])

masked_array(data=[0, 1, 2, 2, 3, 4],
             mask=False,
       fill_value=999999)

In [ ]:
np.ma.concatenate([a, b])

masked_array(data=[0, --, 2, 2, 3, 4],
             mask=[False,  True, False, False, False, False],
       fill_value=999999)