<div class='alert alert-warning'>

NumPy's interactive examples are experimental and may not always work as expected, with high load times especially on low-resource platforms, , and the version of NumPy might not be in sync with the one you are browsing the documentation for. If you encounter any issues, please report them on the [NumPy issue tracker](https://github.com/numpy/numpy/issues).

</div>

In [ ]:
import numpy as np

Given a sequence of a polynomial's zeros:


In [ ]:
np.poly((0, 0, 0)) # Multiple root example

array([1., 0., 0., 0.])

The line above represents z**3 + 0*z**2 + 0*z + 0.


In [ ]:
np.poly((-1./2, 0, 1./2))

array([ 1.  ,  0.  , -0.25,  0.  ])

The line above represents z**3 - z/4


In [ ]:
np.poly((np.random.random(1)[0], 0, np.random.random(1)[0]))

array([ 1.        , -0.77086955,  0.08618131,  0.        ]) # random

Given a square array object:


In [ ]:
P = np.array([[0, 1./3], [-1./2, 0]])
np.poly(P)

array([1.        , 0.        , 0.16666667])

Note how in all cases the leading coefficient is always 1.