<div class='alert alert-warning'>

NumPy's interactive examples are experimental and may not always work as expected, with high load times especially on low-resource platforms, and the version of NumPy might not be in sync with the one you are browsing the documentation for. If you encounter any issues, please report them on the [NumPy issue tracker](https://github.com/numpy/numpy/issues).

</div>

In [ ]:
import numpy as np
a = np.array([1+1j, 1+0j, 4.5, 3, 2, 2j], dtype=complex)
np.isreal(a)

array([False,  True,  True,  True,  True, False])

The function does not work on string arrays.


In [ ]:
a = np.array([2j, "a"], dtype="U")
np.isreal(a)  # Warns about non-elementwise comparison

False

Returns True for all elements in input array of ``dtype=object`` even if
any of the elements is complex.


In [ ]:
a = np.array([1, "2", 3+4j], dtype=object)
np.isreal(a)

array([ True,  True,  True])

isreal should not be used with object arrays


In [ ]:
a = np.array([1+2j, 2+1j], dtype=object)
np.isreal(a)

array([ True,  True])