<div class='alert alert-warning'>

NumPy's interactive examples are experimental and may not always work as expected, with high load times especially on low-resource platforms, , and the version of NumPy might not be in sync with the one you are browsing the documentation for. If you encounter any issues, please report them on the [NumPy issue tracker](https://github.com/numpy/numpy/issues).

</div>

In [ ]:
import numpy as np
element = 2*np.arange(4).reshape((2, 2))
element

array([[0, 2],
       [4, 6]])

In [ ]:
test_elements = [1, 2, 4, 8]
mask = np.isin(element, test_elements)
mask

array([[False,  True],
       [ True, False]])

In [ ]:
element[mask]

array([2, 4])

The indices of the matched values can be obtained with `nonzero`:


In [ ]:
np.nonzero(mask)

(array([0, 1]), array([1, 0]))

The test can also be inverted:


In [ ]:
mask = np.isin(element, test_elements, invert=True)
mask

array([[ True, False],
       [False,  True]])

In [ ]:
element[mask]

array([0, 6])

Because of how `array` handles sets, the following does not
work as expected:


In [ ]:
test_set = {1, 2, 4, 8}
np.isin(element, test_set)

array([[False, False],
       [False, False]])

Casting the set to a list gives the expected result:


In [ ]:
np.isin(element, list(test_set))

array([[False,  True],
       [ True, False]])