<div class='alert alert-warning'>

NumPy's interactive examples are experimental and may not always work as expected, with high load times especially on low-resource platforms, , and the version of NumPy might not be in sync with the one you are browsing the documentation for. If you encounter any issues, please report them on the [NumPy issue tracker](https://github.com/numpy/numpy/issues).

</div>

In [ ]:
import numpy as np

In [ ]:
def square(a, out=None):
    it = np.nditer([a, out],
            flags = ['external_loop', 'buffered'],
            op_flags = [['readonly'],
                        ['writeonly', 'allocate', 'no_broadcast']])
    with it:
        for x, y in it:
            y[...] = x*x
        return it.operands[1]


In [ ]:
square([1,2,3])

array([1, 4, 9])

In [ ]:
b = np.zeros((3,))
square([1,2,3], out=b)

array([1.,  4.,  9.])

In [ ]:
b

array([1.,  4.,  9.])

In [ ]:
square(np.arange(6).reshape(2,3), out=b)

Traceback (most recent call last):
  ...
ValueError: non-broadcastable output operand with shape (3,) doesn't
match the broadcast shape (2,3)