<div class='alert alert-warning'>

NumPy's interactive examples are experimental and may not always work as expected, with high load times especially on low-resource platforms, , and the version of NumPy might not be in sync with the one you are browsing the documentation for. If you encounter any issues, please report them on the [NumPy issue tracker](https://github.com/numpy/numpy/issues).

</div>

Ordinary inner product for vectors:


In [ ]:
import numpy as np
a = np.array([1,2,3])
b = np.array([0,1,0])
np.inner(a, b)

2

Some multidimensional examples:


In [ ]:
a = np.arange(24).reshape((2,3,4))
b = np.arange(4)
c = np.inner(a, b)
c.shape

(2, 3)

In [ ]:
c

array([[ 14,  38,  62],
       [ 86, 110, 134]])

In [ ]:
a = np.arange(2).reshape((1,1,2))
b = np.arange(6).reshape((3,2))
c = np.inner(a, b)
c.shape

(1, 1, 3)

In [ ]:
c

array([[[1, 3, 5]]])

An example where `b` is a scalar:


In [ ]:
np.inner(np.eye(2), 7)

array([[7., 0.],
       [0., 7.]])