<div class='alert alert-warning'>

NumPy's interactive examples are experimental and may not always work as expected, with high load times especially on low-resource platforms, , and the version of NumPy might not be in sync with the one you are browsing the documentation for. If you encounter any issues, please report them on the [NumPy issue tracker](https://github.com/numpy/numpy/issues).

</div>

In [ ]:
import numpy as np
a = np.arange(4).reshape((2,2))
a

array([[0, 1],
       [2, 3]])

In [ ]:
np.min(a)           # Minimum of the flattened array

0

In [ ]:
np.min(a, axis=0)   # Minima along the first axis

array([0, 1])

In [ ]:
np.min(a, axis=1)   # Minima along the second axis

array([0, 2])

In [ ]:
np.min(a, where=[False, True], initial=10, axis=0)

array([10,  1])

In [ ]:
b = np.arange(5, dtype=float)
b[2] = np.nan
np.min(b)

np.float64(nan)

In [ ]:
np.min(b, where=~np.isnan(b), initial=10)

0.0

In [ ]:
np.nanmin(b)

0.0

In [ ]:
np.min([[-50], [10]], axis=-1, initial=0)

array([-50,   0])

Notice that the initial value is used as one of the elements for which the
minimum is determined, unlike for the default argument Python's max
function, which is only used for empty iterables.

Notice that this isn't the same as Python's ``default`` argument.


In [ ]:
np.min([6], initial=5)

5

In [ ]:
min([6], default=5)

6