<div class='alert alert-warning'>

NumPy's interactive examples are experimental and may not always work as expected, with high load times especially on low-resource platforms, , and the version of NumPy might not be in sync with the one you are browsing the documentation for. If you encounter any issues, please report them on the [NumPy issue tracker](https://github.com/numpy/numpy/issues).

</div>

In [ ]:
import numpy as np
arr = np.arange(12).reshape((3, 4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
condition = np.mod(arr, 3)==0
condition

array([[ True, False, False,  True],
       [False, False,  True, False],
       [False,  True, False, False]])

In [ ]:
np.extract(condition, arr)

array([0, 3, 6, 9])

If `condition` is boolean:


In [ ]:
arr[condition]

array([0, 3, 6, 9])