<div class='alert alert-warning'>

NumPy's interactive examples are experimental and may not always work as expected, with high load times especially on low-resource platforms, , and the version of NumPy might not be in sync with the one you are browsing the documentation for. If you encounter any issues, please report them on the [NumPy issue tracker](https://github.com/numpy/numpy/issues).

</div>

In [ ]:
import numpy as np
np.not_equal([1.,2.], [1., 3.])

array([False,  True])

In [ ]:
np.not_equal([1, 2], [[1, 3],[1, 4]])

array([[False,  True],
       [False,  True]])

The ``!=`` operator can be used as a shorthand for ``np.not_equal`` on
ndarrays.


In [ ]:
a = np.array([1., 2.])
b = np.array([1., 3.])
a != b

array([False,  True])