<div class='alert alert-warning'>

NumPy's interactive examples are experimental and may not always work as expected, with high load times especially on low-resource platforms, , and the version of NumPy might not be in sync with the one you are browsing the documentation for. If you encounter any issues, please report them on the [NumPy issue tracker](https://github.com/numpy/numpy/issues).

</div>

In [ ]:
import numpy as np
np.logspace(2.0, 3.0, num=4)

array([ 100.        ,  215.443469  ,  464.15888336, 1000.        ])

In [ ]:
np.logspace(2.0, 3.0, num=4, endpoint=False)

array([100.        ,  177.827941  ,  316.22776602,  562.34132519])

In [ ]:
np.logspace(2.0, 3.0, num=4, base=2.0)

array([4.        ,  5.0396842 ,  6.34960421,  8.        ])

In [ ]:
np.logspace(2.0, 3.0, num=4, base=[2.0, 3.0], axis=-1)

array([[ 4.        ,  5.0396842 ,  6.34960421,  8.        ],
       [ 9.        , 12.98024613, 18.72075441, 27.        ]])

Graphical illustration:


In [ ]:
import matplotlib.pyplot as plt
N = 10
x1 = np.logspace(0.1, 1, N, endpoint=True)
x2 = np.logspace(0.1, 1, N, endpoint=False)
y = np.zeros(N)
plt.plot(x1, y, 'o')

[<matplotlib.lines.Line2D object at 0x...>]

In [ ]:
plt.plot(x2, y + 0.5, 'o')

[<matplotlib.lines.Line2D object at 0x...>]

In [ ]:
plt.ylim([-0.5, 1])

(-0.5, 1)

In [ ]:
plt.show()