<div class='alert alert-warning'>

NumPy's interactive examples are experimental and may not always work as expected, with high load times especially on low-resource platforms, , and the version of NumPy might not be in sync with the one you are browsing the documentation for. If you encounter any issues, please report them on the [NumPy issue tracker](https://github.com/numpy/numpy/issues).

</div>

In [ ]:
from numpy.polynomial import polynomial as P
c = (1, 2, 3, 4)
P.polyder(c)  # (d/dx)(c)

array([  2.,   6.,  12.])

In [ ]:
P.polyder(c, 3)  # (d**3/dx**3)(c)

array([24.])

In [ ]:
P.polyder(c, scl=-1)  # (d/d(-x))(c)

array([ -2.,  -6., -12.])

In [ ]:
P.polyder(c, 2, -1)  # (d**2/d(-x)**2)(c)

array([  6.,  24.])