<div class='alert alert-warning'>

NumPy's interactive examples are experimental and may not always work as expected, with high load times especially on low-resource platforms, , and the version of NumPy might not be in sync with the one you are browsing the documentation for. If you encounter any issues, please report them on the [NumPy issue tracker](https://github.com/numpy/numpy/issues).

</div>

In [ ]:
import numpy as np
m = np.array([[1,2],[3,4]], int)
m

array([[1, 2],
       [3, 4]])

In [ ]:
np.rot90(m)

array([[2, 4],
       [1, 3]])

In [ ]:
np.rot90(m, 2)

array([[4, 3],
       [2, 1]])

In [ ]:
m = np.arange(8).reshape((2,2,2))
np.rot90(m, 1, (1,2))

array([[[1, 3],
        [0, 2]],
       [[5, 7],
        [4, 6]]])