<div class='alert alert-warning'>

NumPy's interactive examples are experimental and may not always work as expected, with high load times especially on low-resource platforms, , and the version of NumPy might not be in sync with the one you are browsing the documentation for. If you encounter any issues, please report them on the [NumPy issue tracker](https://github.com/numpy/numpy/issues).

</div>

In [ ]:
import numpy as np
np.atleast_2d(3.0)

array([[3.]])

In [ ]:
x = np.arange(3.0)
np.atleast_2d(x)

array([[0., 1., 2.]])

In [ ]:
np.atleast_2d(x).base is x

True

In [ ]:
np.atleast_2d(1, [1, 2], [[1, 2]])

(array([[1]]), array([[1, 2]]), array([[1, 2]]))