<div class='alert alert-warning'>

NumPy's interactive examples are experimental and may not always work as expected, with high load times especially on low-resource platforms, , and the version of NumPy might not be in sync with the one you are browsing the documentation for. If you encounter any issues, please report them on the [NumPy issue tracker](https://github.com/numpy/numpy/issues).

</div>

In [ ]:
from numpy.polynomial.laguerre import lagint
lagint([1,2,3])

array([ 1.,  1.,  1., -3.])

In [ ]:
lagint([1,2,3], m=2)

array([ 1.,  0.,  0., -4.,  3.])

In [ ]:
lagint([1,2,3], k=1)

array([ 2.,  1.,  1., -3.])

In [ ]:
lagint([1,2,3], lbnd=-1)

array([11.5,  1. ,  1. , -3. ])

In [ ]:
lagint([1,2], m=2, k=[1,2], lbnd=-1)

array([ 11.16666667,  -5.        ,  -3.        ,   2.        ]) # may vary