<div class='alert alert-warning'>

NumPy's interactive examples are experimental and may not always work as expected, with high load times especially on low-resource platforms, , and the version of NumPy might not be in sync with the one you are browsing the documentation for. If you encounter any issues, please report them on the [NumPy issue tracker](https://github.com/numpy/numpy/issues).

</div>

In [ ]:
import numpy as np

The number 13 is represented by ``00001101``.  Likewise, 17 is
represented by ``00010001``.  The bit-wise AND of 13 and 17 is
therefore ``000000001``, or 1:


In [ ]:
np.bitwise_and(13, 17)

1

In [ ]:
np.bitwise_and(14, 13)

12

In [ ]:
np.binary_repr(12)

'1100'

In [ ]:
np.bitwise_and([14,3], 13)

array([12,  1])

In [ ]:
np.bitwise_and([11,7], [4,25])

array([0, 1])

In [ ]:
np.bitwise_and(np.array([2,5,255]), np.array([3,14,16]))

array([ 2,  4, 16])

In [ ]:
np.bitwise_and([True, True], [False, True])

array([False,  True])

The ``&`` operator can be used as a shorthand for ``np.bitwise_and`` on
ndarrays.


In [ ]:
x1 = np.array([2, 5, 255])
x2 = np.array([3, 14, 16])
x1 & x2

array([ 2,  4, 16])