<div class='alert alert-warning'>

NumPy's interactive examples are experimental and may not always work as expected, with high load times especially on low-resource platforms, , and the version of NumPy might not be in sync with the one you are browsing the documentation for. If you encounter any issues, please report them on the [NumPy issue tracker](https://github.com/numpy/numpy/issues).

</div>

In [ ]:
import numpy as np
x = np.array([1, 2, 4, 7, 0])
np.ediff1d(x)

array([ 1,  2,  3, -7])

In [ ]:
np.ediff1d(x, to_begin=-99, to_end=np.array([88, 99]))

array([-99,   1,   2, ...,  -7,  88,  99])

The returned array is always 1D.


In [ ]:
y = [[1, 2, 4], [1, 6, 24]]
np.ediff1d(y)

array([ 1,  2, -3,  5, 18])