<div class='alert alert-warning'>

NumPy's interactive examples are experimental and may not always work as expected, with high load times especially on low-resource platforms, , and the version of NumPy might not be in sync with the one you are browsing the documentation for. If you encounter any issues, please report them on the [NumPy issue tracker](https://github.com/numpy/numpy/issues).

</div>

In [ ]:
import numpy as np
from numpy import linalg as LA

(Almost) trivial example with real eigenvalues and eigenvectors.


In [ ]:
eigenvalues, eigenvectors = LA.eig(np.diag((1, 2, 3)))
eigenvalues

array([1., 2., 3.])

In [ ]:
eigenvectors

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Real matrix possessing complex eigenvalues and eigenvectors;
note that the eigenvalues are complex conjugates of each other.


In [ ]:
eigenvalues, eigenvectors = LA.eig(np.array([[1, -1], [1, 1]]))
eigenvalues

array([1.+1.j, 1.-1.j])

In [ ]:
eigenvectors

array([[0.70710678+0.j        , 0.70710678-0.j        ],
       [0.        -0.70710678j, 0.        +0.70710678j]])

Complex-valued matrix with real eigenvalues (but complex-valued
eigenvectors); note that ``a.conj().T == a``, i.e., `a` is Hermitian.


In [ ]:
a = np.array([[1, 1j], [-1j, 1]])
eigenvalues, eigenvectors = LA.eig(a)
eigenvalues

array([2.+0.j, 0.+0.j])

In [ ]:
eigenvectors

array([[ 0.        +0.70710678j,  0.70710678+0.j        ], # may vary
       [ 0.70710678+0.j        , -0.        +0.70710678j]])

Be careful about round-off error!


In [ ]:
a = np.array([[1 + 1e-9, 0], [0, 1 - 1e-9]])
# Theor. eigenvalues are 1 +/- 1e-9
eigenvalues, eigenvectors = LA.eig(a)
eigenvalues

array([1., 1.])

In [ ]:
eigenvectors

array([[1., 0.],
       [0., 1.]])