<div class='alert alert-warning'>

NumPy's interactive examples are experimental and may not always work as expected, with high load times especially on low-resource platforms, , and the version of NumPy might not be in sync with the one you are browsing the documentation for. If you encounter any issues, please report them on the [NumPy issue tracker](https://github.com/numpy/numpy/issues).

</div>

In [ ]:
import numpy as np
f = np.array([1, 2, 4, 7, 11, 16])
np.gradient(f)

array([1. , 1.5, 2.5, 3.5, 4.5, 5. ])

In [ ]:
np.gradient(f, 2)

array([0.5 ,  0.75,  1.25,  1.75,  2.25,  2.5 ])

Spacing can be also specified with an array that represents the coordinates
of the values F along the dimensions.
For instance a uniform spacing:


In [ ]:
x = np.arange(f.size)
np.gradient(f, x)

array([1. ,  1.5,  2.5,  3.5,  4.5,  5. ])

Or a non uniform one:


In [ ]:
x = np.array([0., 1., 1.5, 3.5, 4., 6.])
np.gradient(f, x)

array([1. ,  3. ,  3.5,  6.7,  6.9,  2.5])

For two dimensional arrays, the return will be two arrays ordered by
axis. In this example the first array stands for the gradient in
rows and the second one in columns direction:


In [ ]:
np.gradient(np.array([[1, 2, 6], [3, 4, 5]]))

(array([[ 2.,  2., -1.],
        [ 2.,  2., -1.]]),
 array([[1. , 2.5, 4. ],
        [1. , 1. , 1. ]]))

In this example the spacing is also specified:
uniform for axis=0 and non uniform for axis=1


In [ ]:
dx = 2.
y = [1., 1.5, 3.5]
np.gradient(np.array([[1, 2, 6], [3, 4, 5]]), dx, y)

(array([[ 1. ,  1. , -0.5],
        [ 1. ,  1. , -0.5]]),
 array([[2. , 2. , 2. ],
        [2. , 1.7, 0.5]]))

It is possible to specify how boundaries are treated using `edge_order`


In [ ]:
x = np.array([0, 1, 2, 3, 4])
f = x**2
np.gradient(f, edge_order=1)

array([1.,  2.,  4.,  6.,  7.])

In [ ]:
np.gradient(f, edge_order=2)

array([0., 2., 4., 6., 8.])

The `axis` keyword can be used to specify a subset of axes of which the
gradient is calculated


In [ ]:
np.gradient(np.array([[1, 2, 6], [3, 4, 5]]), axis=0)

array([[ 2.,  2., -1.],
       [ 2.,  2., -1.]])

The `varargs` argument defines the spacing between sample points in the
input array. It can take two forms:

1. An array, specifying coordinates, which may be unevenly spaced:


In [ ]:
x = np.array([0., 2., 3., 6., 8.])
y = x ** 2
np.gradient(y, x, edge_order=2)

array([ 0.,  4.,  6., 12., 16.])

2. A scalar, representing the fixed sample distance:


In [ ]:
dx = 2
x = np.array([0., 2., 4., 6., 8.])
y = x ** 2
np.gradient(y, dx, edge_order=2)

array([ 0.,  4.,  8., 12., 16.])

It's possible to provide different data for spacing along each dimension.
The number of arguments must match the number of dimensions in the input
data.


In [ ]:
dx = 2
dy = 3
x = np.arange(0, 6, dx)
y = np.arange(0, 9, dy)
xs, ys = np.meshgrid(x, y)
zs = xs + 2 * ys
np.gradient(zs, dy, dx)  # Passing two scalars

(array([[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]]),
 array([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]))

Mixing scalars and arrays is also allowed:


In [ ]:
np.gradient(zs, y, dx)  # Passing one array and one scalar

(array([[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]]),
 array([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]))