<div class='alert alert-warning'>

NumPy's interactive examples are experimental and may not always work as expected, with high load times especially on low-resource platforms, , and the version of NumPy might not be in sync with the one you are browsing the documentation for. If you encounter any issues, please report them on the [NumPy issue tracker](https://github.com/numpy/numpy/issues).

</div>

In [ ]:
import numpy as np
a = np.array([1, 2])
a.fill(0)
a

array([0, 0])

In [ ]:
a = np.empty(2)
a.fill(1)
a

array([1.,  1.])

Fill expects a scalar value and always behaves the same as assigning
to a single array element.  The following is a rare example where this
distinction is important:


In [ ]:
a = np.array([None, None], dtype=object)
a[0] = np.array(3)
a

array([array(3), None], dtype=object)

In [ ]:
a.fill(np.array(3))
a

array([array(3), array(3)], dtype=object)

Where other forms of assignments will unpack the array being assigned:


In [ ]:
a[...] = np.array(3)
a

array([3, 3], dtype=object)