<div class='alert alert-warning'>

NumPy's interactive examples are experimental and may not always work as expected, with high load times especially on low-resource platforms, , and the version of NumPy might not be in sync with the one you are browsing the documentation for. If you encounter any issues, please report them on the [NumPy issue tracker](https://github.com/numpy/numpy/issues).

</div>

In [ ]:
import numpy as np
from numpy import linalg as LA
a = np.array([[1, -2j], [2j, 5]])
a

array([[ 1.+0.j, -0.-2.j],
       [ 0.+2.j,  5.+0.j]])

In [ ]:
eigenvalues, eigenvectors = LA.eigh(a)
eigenvalues

array([0.17157288, 5.82842712])

In [ ]:
eigenvectors

array([[-0.92387953+0.j        , -0.38268343+0.j        ], # may vary
       [ 0.        +0.38268343j,  0.        -0.92387953j]])

In [ ]:
(np.dot(a, eigenvectors[:, 0]) -
eigenvalues[0] * eigenvectors[:, 0])  # verify 1st eigenval/vec pair

array([5.55111512e-17+0.0000000e+00j, 0.00000000e+00+1.2490009e-16j])

In [ ]:
(np.dot(a, eigenvectors[:, 1]) -
eigenvalues[1] * eigenvectors[:, 1])  # verify 2nd eigenval/vec pair

array([0.+0.j, 0.+0.j])

In [ ]:
A = np.matrix(a) # what happens if input is a matrix object
A

matrix([[ 1.+0.j, -0.-2.j],
        [ 0.+2.j,  5.+0.j]])

In [ ]:
eigenvalues, eigenvectors = LA.eigh(A)
eigenvalues

array([0.17157288, 5.82842712])

In [ ]:
eigenvectors

matrix([[-0.92387953+0.j        , -0.38268343+0.j        ], # may vary
        [ 0.        +0.38268343j,  0.        -0.92387953j]])

In [ ]:
# demonstrate the treatment of the imaginary part of the diagonal
a = np.array([[5+2j, 9-2j], [0+2j, 2-1j]])
a

array([[5.+2.j, 9.-2.j],
       [0.+2.j, 2.-1.j]])

In [ ]:
# with UPLO='L' this is numerically equivalent to using LA.eig() with:
b = np.array([[5.+0.j, 0.-2.j], [0.+2.j, 2.-0.j]])
b

array([[5.+0.j, 0.-2.j],
       [0.+2.j, 2.+0.j]])

In [ ]:
wa, va = LA.eigh(a)
wb, vb = LA.eig(b)
wa; wb

array([1., 6.])
array([6.+0.j, 1.+0.j])

In [ ]:
va; vb

array([[-0.4472136 +0.j        , -0.89442719+0.j        ], # may vary
       [ 0.        +0.89442719j,  0.        -0.4472136j ]])
array([[ 0.89442719+0.j       , -0.        +0.4472136j],
       [-0.        +0.4472136j,  0.89442719+0.j       ]])