<div class='alert alert-warning'>

NumPy's interactive examples are experimental and may not always work as expected, with high load times especially on low-resource platforms, , and the version of NumPy might not be in sync with the one you are browsing the documentation for. If you encounter any issues, please report them on the [NumPy issue tracker](https://github.com/numpy/numpy/issues).

</div>

In [ ]:
import numpy as np
grid = np.indices((2, 3))
grid.shape

(2, 2, 3)

In [ ]:
grid[0]        # row indices

array([[0, 0, 0],
       [1, 1, 1]])

In [ ]:
grid[1]        # column indices

array([[0, 1, 2],
       [0, 1, 2]])

The indices can be used as an index into an array.


In [ ]:
x = np.arange(20).reshape(5, 4)
row, col = np.indices((2, 3))
x[row, col]

array([[0, 1, 2],
       [4, 5, 6]])

Note that it would be more straightforward in the above example to
extract the required elements directly with ``x[:2, :3]``.

If sparse is set to true, the grid will be returned in a sparse
representation.


In [ ]:
i, j = np.indices((2, 3), sparse=True)
i.shape

(2, 1)

In [ ]:
j.shape

(1, 3)

In [ ]:
i        # row indices

array([[0],
       [1]])

In [ ]:
j        # column indices

array([[0, 1, 2]])