<div class='alert alert-warning'>

NumPy's interactive examples are experimental and may not always work as expected, with high load times especially on low-resource platforms, , and the version of NumPy might not be in sync with the one you are browsing the documentation for. If you encounter any issues, please report them on the [NumPy issue tracker](https://github.com/numpy/numpy/issues).

</div>

Create an array with two fields, ``x`` and ``y``:


In [ ]:
import numpy as np
x = np.array([(1.0, 2), (3.0, 4)], dtype=[('x', '<f8'), ('y', '<i8')])
x

array([(1., 2), (3., 4)], dtype=[('x', '<f8'), ('y', '<i8')])

In [ ]:
x['x']

array([1., 3.])

View the array as a record array:


In [ ]:
x = x.view(np.recarray)

In [ ]:
x.x

array([1., 3.])

In [ ]:
x.y

array([2, 4])

Create a new, empty record array:


In [ ]:
np.recarray((2,),
dtype=[('x', int), ('y', float), ('z', int)]) #doctest: +SKIP

rec.array([(-1073741821, 1.2249118382103472e-301, 24547520),
       (3471280, 1.2134086255804012e-316, 0)],
      dtype=[('x', '<i4'), ('y', '<f8'), ('z', '<i4')])